### ISSUE TITLE
[Bug]: Vehicle Gift Doesn't Work

### ISSUE THREAD

**Issue by Delisten** [Deadlineem/Extras-Addon-for-YimMenu#100]
### Description

When pressing "gift vehicle" button, the giftee gets kicked from the vehicle.

### Steps to Reproduce

Drive out of garage, drive back in, walk out, giftee gets in vehicle, gifter presses gift button, giftee gets kicked.

### Version

- [X] I've confirmed the issue exists on the latest version

**Comment by USBMenus** [comment]
im pretty sure its patched, just hasnt been removed from the script yet

**Comment by Delisten** [comment]
is there any alternatives to gifting cars?

**Comment by Deadlineem** [comment]
> is there any alternatives to gifting cars?

Unfortunately, no, not at this time.  Even paid menus like Stand and 2Take1 got the gifting system patched as well.

**Comment by Deadlineem** [comment]
closing as duplicate of #98 it will get fixed as soon as there are some workarounds.
