### ISSUE TITLE
[Request]: Tunables 

### ISSUE THREAD

**Issue by rr1231234** [Deadlineem/Extras-Addon-for-YimMenu#103]
### Request

Tunables for RP, Car meet...

Thanks.

**Comment by Deadlineem** [comment]
> ### Request
> 
> Tunables for RP, Car meet...
> 
> Thanks.

Player Options > Stats 

You cna change your rp to any level you desire and if you click that unlock all button, your car meet rep will be 1000

**Comment by rr1231234** [comment]
Yes but I need to pause the level gaining so it will stay at 420 without changing back so often

**Comment by USBMenus** [comment]
I think kiddions had an rp multiplier, maybe we can do something like that and just set it to 0

**Comment by Deadlineem** [comment]
> Yes but I need to pause the level gaining so it will stay at 420 without changing back so often

@USBMenus and I may have found a way to stop RP gain for this, but it would be a feature you would have to toggle on.

Maybe we can append this into the config so when its toggled on or off, it saves the toggle state and reloads it next time you load in?

**Comment by USBMenus** [comment]
pushed an update and added rp multiplier in player options -> stats
