### ISSUE TITLE
[Improvement]: Improve Clown Jet Attack

### ISSUE THREAD

**Issue by Donald-Trump-Maga** [Deadlineem/Extras-Addon-for-YimMenu#105]
### Request

I wanted to ask for a small request. Can you make it so that fighters don't fall like stones when a player leaves the game or for what reason do they do this? but simply so that they switch to another player or to an NPC. it would be a little more fun

**Comment by Deadlineem** [comment]
> ### Request
> 
> I wanted to ask for a small request. Can you make it so that fighters don't fall like stones when a player leaves the game or for what reason do they do this? but simply so that they switch to another player or to an NPC. it would be a little more fun

Then the jets have nothing to attack because the player left or died, they no longer have an objective so they crash and burn.  This is for two reasons 1.  So it does not overpopulate the session and 2. because im not sure if there is a way to make it target another player after one quits

**Comment by Deadlineem** [comment]
Jets now continuously attack their targets.
