### ISSUE TITLE
[Bug]: Crash using "NPCs drive to this player" while spectating or near player

### ISSUE THREAD

**Issue by zobal12** [Deadlineem/Extras-Addon-for-YimMenu#107]
### Description

Game crashes after using grief option "NPCs drive to this player" on other player if near or spectating, but most common while spectating.

### Steps to Reproduce

1. Go near other player or spectate other player
2. Use grief option "NPCs drive to this player" on other player 
3. Observe crash

### Screenshots

https://github.com/user-attachments/assets/e03bda06-4c15-48e4-ba8f-5ecfe9d403f1

### Additional Information

Through testing, i have also observed a crash when using the grief option on someone and then spectating a different person, might be important to note.

Crash could possibly also happen if not near and not spectating, however i have not observed it myself. 

Seems to happen regardless of being host or not.

Here's the log i got after a crash:
[cout.log](https://github.com/user-attachments/files/16360686/cout.log)

Tested on latest Extra addons installed using update.bat, and latest NIGHTLY yim commit c975a14. Also happened on previous versions of yim menu.

### Version

- [x] I've confirmed the issue exists on the latest version

**Comment by USBMenus** [comment]
should be fixed

**Comment by zobal12** [comment]
Have you tested it? When i tried the new file, the option didn't work at all. Crashes seem to still be present. Maybe a configuration issue on my side, i'm not sure.

**Comment by USBMenus** [comment]
> Have you tested it? When i tried the new file, the option didn't work at all. Crashes seem to still be present. Maybe a configuration issue on my side, i'm not sure.

i did before i pushed it, it worked for me, but when i tried it again i crashed, i think i fixed it this time if you wanna test it

**Comment by zobal12** [comment]
Can confirm it works now, thanks for the quick work 👍

**Comment by zobal12** [comment]
I did crash a few minutes after using it. 
[cout.log](https://github.com/user-attachments/files/16376983/cout.log)

**Comment by zobal12** [comment]
Confirmed crash still happens occasionally.

**Comment by lokislokis** [comment]
Was working fine earlier today but now it seems to crash every single time within a minute of using it 
Tried reloading cache and reinstalling but to no avail 
[cout.log](https://github.com/user-attachments/files/16398654/cout.log)

**Comment by USBMenus** [comment]
pushed an update, it should hopefully be fixed now

**Comment by zobal12** [comment]
Works as intended now

**Comment by infinity-stack** [comment]
is there an update?

**Comment by Deadlineem** [comment]
> is there an update?

Pretty sure theres been a few already since this was one of the issues fixed.

**Comment by Deadlineem** [comment]
> where can i see the updates cause i checked the files and they are all like 2 weeks or months ago

Extras-Addon.lua was updated 6 hours ago,

**Comment by infinity-stack** [comment]
does this mean it works but sometimes crash?

**Comment by ItzTyrone** [comment]
still crashing for me after 30 seconds of use

**Comment by Deadlineem** [comment]
> still crashing for me after 30 seconds of use

@USBMenus i will also take a look at this one later on as well see if i can figure out the issue.

**Comment by Deadlineem** [comment]
> does this mean it works but sometimes crash?

I dont use the NPC drive option often but i have never crashed personally from using it even before these reports.  Ill tedt it later tonight and see what the deal is here.

**Comment by ItzTyrone** [comment]
where are logs stored? I can upload mine if it helps

**Comment by Deadlineem** [comment]
> where are logs stored? I can upload mine if it helps

Unless is specifically shows extras-addon in the logs it doesn't help much.  The issues are with the request_control and get vehicle ped is using, which are needed for NPC drive to work.  Expect to see this temporarily disabled like the vehicle spawner tab until its sorted.

**Comment by Deadlineem** [comment]
All fixed now, there was an issue with out request_control on the NPC's

**Comment by zobal12** [comment]
Super, thanks 👍

**Comment by zobal12** [comment]
Seems to crash again. Please test the option for yourself. Not gonna open issue yet, unless crashes are confirmed again.
