### ISSUE TITLE
[Bug]: Vehicle Ram does nothing

### ISSUE THREAD

**Issue by lokislokis** [Deadlineem/Extras-Addon-for-YimMenu#108]
### Description

Vehicle Ram does not do what it says and simply errors: "attempt to call a nil value (global 'max_vehicle')"

### Steps to Reproduce

1. Select player and attempt to vehicle ram
2. nothing happens

### Additional Information

[cout.log](https://github.com/user-attachments/files/16402350/cout.log)

### Version

- [X] I've confirmed the issue exists on the latest version

**Comment by Deadlineem** [comment]
Fixed

**Comment by lokislokis** [comment]
Thank you! Works as intended now
