### ISSUE TITLE
[Bug]: Heist editor and Forcefield/Magnetfield not working

### ISSUE THREAD

**Issue by Kibasmoothie** [Deadlineem/Extras-Addon-for-YimMenu#109]
### Description

The Forcefield and magentfield jsut doesnt do anything. The heist editor works flawlessly but the bring everyone is non functional and the remove CCTV is also not doing anything

### Steps to Reproduce

1. Go to Forcefield
2. do anything
3. not working

1.Go to Cayo and do the heist
2. try the teleport
3. not doing anything
4. try the cctv remove
5. not working

### Additional Information

No clue how to fix this as i dont code.
a chinese script with a english translation has a working forcefield tho and also ahs a working remove cctv maybe skid it and steal it lol

### Version

- [X] I've confirmed the issue exists on the latest version

**Comment by Deadlineem** [comment]
> ### Description
> The Forcefield and magentfield jsut doesnt do anything. The heist editor works flawlessly but the bring everyone is non functional and the remove CCTV is also not doing anything
> 
> ### Steps to Reproduce
> 1. Go to Forcefield
> 2. do anything
> 3. not working
> 
> 1.Go to Cayo and do the heist 2. try the teleport 3. not doing anything 4. try the cctv remove 5. not working
> 
> ### Screenshots
> _No response_
> 
> ### Additional Information
> No clue how to fix this as i dont code. a chinese script with a english translation has a working forcefield tho and also ahs a working remove cctv maybe skid it and steal it lol
> 
> ### Version
> * [x]  I've confirmed the issue exists on the latest version

Select a player name from YimMenu's player list (Yourself or someone else + spectate) THEN activate the magnet/forcefield.  It works flawlessly its just a selected player feature.

Teleports/etc. in cayo should work I will check these later tonight.

**Comment by Kibasmoothie** [comment]
Ohhhhhh ok ty yeah i realized the select a player and do that feature after i made my friend do heelflips and wondered why it didnt work for me lol didnt know its select.
Would it also be possible to rearrange the grief and drop menus on players permanently? If you get what i mean

**Comment by Deadlineem** [comment]
> Ohhhhhh ok ty yeah i realized the select a player and do that feature after i made my friend do heelflips and wondered why it didnt work for me lol didnt know its select. Would it also be possible to rearrange the grief and drop menus on players permanently? If you get what i mean

Yes, alot of options are selectable and are not specified that they are selectable.

Do you mean how they are positioned?  We are making plans to rework this addon but as far as the tabs go you can select a player and place the tabs where you want them to be by dragging them around, any time you click that players name in the list it will show up in that new location, but it will default its position when a different player is selected.

**Comment by Kibasmoothie** [comment]
Yeah i mean change the default position so no matter which player its in the same NEW default position

**Comment by rjp421** [comment]
The Cayo Heist Editor "Bring Everyone" will only bring players who are 50 meters away.

Sometimes it will not work because they are too close, and/or sometimes needs a couple clicks to actually bring everyone.

Delete CCTVs has caused me to crash, but i have not submitted an issue feeling like its just me crashing.

**Comment by Deadlineem** [comment]
> The Cayo Heist Editor "Bring Everyone" will only bring players who are 50 meters away.
> 
> Sometimes it will not work because they are too close, and/or sometimes needs a couple clicks to actually bring everyone.
> 
> Delete CCTVs has caused me to crash, but i have not submitted an issue feeling like its just me crashing.

@USBMenus Should we should iterate over the bring command a few times inside itself and increase the range a bit?

As for CCTV im not sure what happened here but i will look into it as soon as i get home

**Comment by USBMenus** [comment]
> @USBMenus Should we should iterate over the bring command a few times inside itself and increase the range a bit?
> 
> As for CCTV im not sure what happened here but i will look into it as soon as i get home

i made it tp everyone further than 50m cause it doesnt work sometimes and tping the same people over and over would prolly be annoying

**Comment by rr1231234** [comment]
Off topic but does this apartment 15mil cut for others still working?
![a](https://github.com/user-attachments/assets/9f0cee65-b815-4698-a225-862e163880ad)

**Comment by infinity-stack** [comment]
yes wwhat is the problem

**Comment by Deadlineem** [comment]
> Off topic but does this apartment 15mil cut for others still working? ![a](https://private-user-images.githubusercontent.com/92568853/353742923-9f0cee65-b815-4698-a225-862e163880ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0OTYzOTUsIm5iZiI6MTcyMjQ5NjA5NSwicGF0aCI6Ii85MjU2ODg1My8zNTM3NDI5MjMtOWYwY2VlNjUtYjgxNS00Njk4LWEyMjUtODYyZTE2Mzg4MGFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDA3MDgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0NzExMDc5ZjYxYzMxMzE2N2FmOTdjOWQxNTQxZWQzZDBkMWZiZmVkNTc2M2FjMThlZGVlMGRmODI4NzE4MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Xctfkc8IA4XJp2YjwVTBmbuPAzoJG2nxNiYIydHDLMY)

It is working but its a bit tricky to get it to work properly.

First you launch the mission
Then on the planning screen where you select a prep, click complete preps
Then walk to the board and access it
Start the heist and skip the initial cutscene as soon as u can
Once youre on the planning board, HOVER over your cut only do not access it just hover 

Now press 15 mill cuts and it will change

Then launch the mission and complete it do not die or quick restart otherwise u wont get anything.

**Comment by rr1231234** [comment]
@Deadlineem thanks bud, I'll try today and hopefully all 4 players get 15mil

**Comment by rr1231234** [comment]
> > Off topic but does this apartment 15mil cut for others still working? ![a](https://private-user-images.githubusercontent.com/92568853/353742923-9f0cee65-b815-4698-a225-862e163880ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0OTYzOTUsIm5iZiI6MTcyMjQ5NjA5NSwicGF0aCI6Ii85MjU2ODg1My8zNTM3NDI5MjMtOWYwY2VlNjUtYjgxNS00Njk4LWEyMjUtODYyZTE2Mzg4MGFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDA3MDgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0NzExMDc5ZjYxYzMxMzE2N2FmOTdjOWQxNTQxZWQzZDBkMWZiZmVkNTc2M2FjMThlZGVlMGRmODI4NzE4MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Xctfkc8IA4XJp2YjwVTBmbuPAzoJG2nxNiYIydHDLMY)
> 
> It is working but its a bit tricky to get it to work properly.
> 
> First you launch the mission Then on the planning screen where you select a prep, click complete preps and press up or down it should kick u off the board
> 
> Then walk to the board and access it again Start the heist and skip the initial cutscene as soon as u can Once youre on the planning board, HOVER over your cut only do not access it just hover
> 
> Now press 15 mill cuts and it will change
> 
> Then launch the mission and complete it do not die or quick restart otherwise u wont get anything.

So I did this today but got transaction error, other 3 guys wont get money either

Hover and click 15m cuts as instructed

**Comment by Deadlineem** [comment]
> > > Off topic but does this apartment 15mil cut for others still working? ![a](https://private-user-images.githubusercontent.com/92568853/353742923-9f0cee65-b815-4698-a225-862e163880ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0OTYzOTUsIm5iZiI6MTcyMjQ5NjA5NSwicGF0aCI6Ii85MjU2ODg1My8zNTM3NDI5MjMtOWYwY2VlNjUtYjgxNS00Njk4LWEyMjUtODYyZTE2Mzg4MGFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDA3MDgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0NzExMDc5ZjYxYzMxMzE2N2FmOTdjOWQxNTQxZWQzZDBkMWZiZmVkNTc2M2FjMThlZGVlMGRmODI4NzE4MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Xctfkc8IA4XJp2YjwVTBmbuPAzoJG2nxNiYIydHDLMY)
> > 
> > 
> > It is working but its a bit tricky to get it to work properly.
> > First you launch the mission Then on the planning screen where you select a prep, click complete preps and press up or down it should kick u off the board
> > Then walk to the board and access it again Start the heist and skip the initial cutscene as soon as u can Once youre on the planning board, HOVER over your cut only do not access it just hover
> > Now press 15 mill cuts and it will change
> > Then launch the mission and complete it do not die or quick restart otherwise u wont get anything.
> 
> So I did this today but got transaction error, other 3 guys wont get money either
> 
> Hover and click 15m cuts as instructed

Saw on silents discord that the 15 mill cuts may have been patched/detected, i don't use or advise using them.  @USBMenus
