### ISSUE TITLE
[Bug]: vehicle ram doesn't work

### ISSUE THREAD

**Issue by infinity-stack** [Deadlineem/Extras-Addon-for-YimMenu#110]
### Description

I tried vehicle rams on people with different velocities and delays but there is still nothing

### Steps to Reproduce

Go to a player's name 
press grief
click vehicle ram
nothing

### Version

- [X] I've confirmed the issue exists on the latest version

**Comment by Deadlineem** [comment]
Update the extras-addon.lua and try again, works for me just fine.

**Comment by infinity-stack** [comment]
my mistake i just did that haha
