### ISSUE TITLE
[Request]: add the same amount (15 million) to casino heist, cayo perico and doomsday heists

### ISSUE THREAD

**Issue by infinity-stack** [Deadlineem/Extras-Addon-for-YimMenu#111]
### Request

I like how you did the old heists with 15 million but it would be better if it were possible with casino cayo and doomsday if you could do that a lot of people would appreciate it especially me.

**Comment by USBMenus** [comment]
> ### Request
> I like how you did the old heists with 15 million but it would be better if it were possible with casino cayo and doomsday if you could do that a lot of people would appreciate it especially me.

apartment heists are the only ones you can get 15 mil from, all others max out at around 4 mil, any more will give you a transaction error
