### ISSUE TITLE
[Bug]: Some of the bunker submenu options don't seem to work?

### ISSUE THREAD

**Issue by servoskull0** [Deadlineem/Extras-Addon-for-YimMenu#112]
### Description

So basically I tried to unlock all researches and use the fast production thing, but they didn't affect anything no matter what I did. 
I did a clear YimMenu reinstall, disabled all scripts except for this one, but the problem is still there.

### Steps to Reproduce

1. Launch game
2. Story mode
3. Inject YimMenu with Fate Client 
4. Online mode
5. Business manager > Bunker > Unlock all researches
6. Business manager > Bunker > Fast Production

### Screenshots

https://imgur.com/a/0yanhOj

### Version

- [X] I've confirmed the issue exists on the latest version

**Comment by Deadlineem** [comment]
NOTE:  If you have went into Player Options > Stats > Unlock All

There is no need to use the unlock research option.

I can confirm these do not work currently, unsure why.  Fast production does not seem to work at all anymore, removing them since they are kinda useless with the unlock all.
