### ISSUE TITLE
[Bug]: Crash using "NPCs drive to this player" while spectating or near player

### ISSUE THREAD

**Issue by THEKILERFRIEND** [Deadlineem/Extras-Addon-for-YimMenu#115]
### Description

3 seconds after turning it on, I crashed. I am on the latest version. this feature worked before the last update. idk wut happened.

### Steps to Reproduce

1. enable npc drive to this player 2. crash.

### Screenshots

![image](https://github.com/user-attachments/assets/d184583f-2c88-4771-bca1-0846862124a8)

### Version

- [X] I've confirmed the issue exists on the latest version

**Comment by zobal12** [comment]
Can confirm this happens, also duplicate

**Comment by Deadlineem** [comment]
Removing NPC Drive bc of this.  I tried/tested this for a few days working on it trying to get it working right, it's just useless now fr.
