### ISSUE TITLE
[Bug]: casino rig doesn't work for people

### ISSUE THREAD

**Issue by infinity-stack** [Deadlineem/Extras-Addon-for-YimMenu#116]
### Description

everytime i turn on roulette rig it makes people not be able to sit down

### Steps to Reproduce

Go to money options press casino press activate roulette rig next is people arent able to sit

### Version

- [X] I've confirmed the issue exists on the latest version

**Comment by Deadlineem** [comment]
I was just using this last night/this morning

1. Make sure they are in the casino and have chips
2. Make sure the players who want to play either
 -- Own a Casino Penthouse
 OR
 -- Are in a CEO/MC with someone who owns a penthouse
 
Slide the slider to your desired winning number, activate and then have them sit.  Should work fine.

**Comment by infinity-stack** [comment]
it won't let them sit for some reason and I put them in my motorcycle club

**Comment by Deadlineem** [comment]
> it won't let them sit for some reason and I put them in my motorcycle club

Make a new public or invite only session and invite them then try again.  I dont recommend doing this in public lobbies that have had modders, it bugs out.
