### ISSUE TITLE
[Bug]: pacific standard heist cuts are bugged

### ISSUE THREAD

**Issue by infinity-stack** [Deadlineem/Extras-Addon-for-YimMenu#117]
### Description

I don't know if the old heists are bugged too but only two people from the heist get the 15 million cuts but not the other two

### Steps to Reproduce

Go to your cut press 15 million cut (its on normal) only 2 people get the 15 million cut

### Version

- [X] I've confirmed the issue exists on the latest version

**Comment by USBMenus** [comment]
you have to select the heist youre on from the list before clicking the 15 mil button

**Comment by infinity-stack** [comment]
holy shit i forgot oh my god thank you

**Comment by Deadlineem** [comment]
> holy shit i forgot oh my god thank you

We are considering making this auto-select based on the heist youre in to prevent this very thing lol
