### ISSUE TITLE
[Problem] Downloading YimMenu/FateInjector does not work if the Downloads folder has been moved

### ISSUE THREAD

**Issue by byDaveCC** [Deadlineem/Extras-Addon-for-YimMenu#12]
Downloading YimMenu/FateInjector with update.bat does not work if the user has moved the Downloads folder from %USERPROFILE%\Downloads to a different directory and it ceases to exist, e.g. I moved the Downloads folder to F:\Downloads, so there is no "Downloads" folder in %USERPROFILE%.
![Screenshot 2024-02-24 115240](https://github.com/Deadlineem/Extras-Addon-for-YimMenu/assets/122679053/c6ed4c70-4416-400f-8f66-c5372a14d571)

**Comment by Deadlineem** [comment]
@byDaveCC 

May need to either create the folder, or send it to the desktop, instead.  What are your suggestions?

**Comment by Deadlineem** [comment]
Batch file updated to default to desktop filepaths if the application cannot find the downloads directory on the corresponding drive.
