### ISSUE TITLE
[Bug]: Big con diamond casino crashes

### ISSUE THREAD

**Issue by infinity-stack** [Deadlineem/Extras-Addon-for-YimMenu#121]
### Description

everytime i am ready to do the casino heist when I tap the exit choices it crashes me but when I do the big con it says its broken

### Steps to Reproduce

Go to heist editor
Press casino heist
tap big con

### Screenshots

![20240809162606_1](https://github.com/user-attachments/assets/910752c1-cf9a-40ff-a3b7-7d6cdcfdca25)

### Version

- [X] I've confirmed the issue exists on the latest version

**Comment by Deadlineem** [comment]
Fixed, Updated, Closed.
