### ISSUE TITLE
[Bug]: Pacific standard heist cut doesn't work

### ISSUE THREAD

**Issue by infinity-stack** [Deadlineem/Extras-Addon-for-YimMenu#122]
### Description

this time i pressed pacific standard heist but the cut only affects me no one else

### Steps to Reproduce

Go to pacific standard heist
Tap 15 million cut
Nothing works

### Additional Information

I did the instructions

### Version

- [X] I've confirmed the issue exists on the latest version

**Comment by USBMenus** [comment]
you have to run it on normal, then hover over your cut on the planning screen and click the button, wait about 2 seconds and everyone should have 15mil cuts, if you fail youll have to fully restart(not quick restart) or it wont give the money

**Comment by infinity-stack** [comment]
i did i can show u a pic

**Comment by infinity-stack** [comment]
![20240809223258_1](https://github.com/user-attachments/assets/923825ca-99d4-42bd-b774-bae0479f45f4)

**Comment by infinity-stack** [comment]
![20240809223330_1](https://github.com/user-attachments/assets/662a257e-5b42-45df-9178-64667cfd0421)

**Comment by USBMenus** [comment]
dont click on your cut, just hover over it, also you need to click it within the first 30 seconds of seeing the planning screen

**Comment by infinity-stack** [comment]
but i did hover and wait cause someone needed to do something so we waited

**Comment by USBMenus** [comment]
you have to click the `15 Million Cuts` button within the first 30 seconds, if you wait itll mess it up

**Comment by infinity-stack** [comment]
i did though
