### ISSUE TITLE
[Bug]: The casino exit choice still crashes

### ISSUE THREAD

**Issue by infinity-stack** [Deadlineem/Extras-Addon-for-YimMenu#131]
### Description

i think its something with the log but it keeps doing it

### Steps to Reproduce

Go to arcade
register as boss
press finale board
go to exit
crashed

### Screenshots

[cout.log](https://github.com/user-attachments/files/16577992/cout.log)

### Additional Information

i tried rockstar upport but it doesnt work

### Version

- [X] I've confirmed the issue exists on the latest version

**Comment by infinity-stack** [comment]
and for some reason complete all setups don't work

**Comment by Deadlineem** [comment]
Now i know youre on the wrong version of the addon @infinity-stack because casino heists do not have a complete all setups option anymore.  I reworked the casino options the other day when you posted something about "the big con".  Update your scripts.

also, why would you try R* support on a mod addon?

**Comment by infinity-stack** [comment]
nooo cause i kept crashing about the casino exit choice i never said anything to rockstar about you guys

**Comment by Deadlineem** [comment]
> nooo cause i kept crashing about the casino exit choice i never said anything to rockstar about you guys

You do know they will manually monitor your account for that kind of thing while checking for issues, right?

**Comment by infinity-stack** [comment]
really?

**Comment by infinity-stack** [comment]
i bribed them

**Comment by Deadlineem** [comment]
@infinity-stack update your scripts and check the casino options now.  I did some more changes, they seem to work well now.
