### ISSUE TITLE
[Request]: Toggle to disable car windows collision 

### ISSUE THREAD

**Issue by rr1231234** [Deadlineem/Extras-Addon-for-YimMenu#132]
### Request

Same as a Modest menu's ToggleWindowCollisionsDisabled: to prevent car windows from breaking by allowing objects like your arm or bullets clipping through:

![353892853-f6f4867d-f67c-45cb-a2ec-f67d3941b325](https://github.com/user-attachments/assets/374201d5-5342-423d-b81c-aecc5d77f35c)

Better cosmetic, no more messy broken windows when driveby shooting. I used this a lot on modest menu and happen to see someone using it today (with a different menu).

**Comment by Deadlineem** [comment]
// 0x1087BC8EC540DAEB b1103

void SET_​DONT_​PROCESS_​VEHICLE_​GLASS(
Vehicle vehicle,
BOOL toggle
)

ped = PLAYER.PLAYER_PED_ID()
veh = VEHICLE.GET_VEHICLE_PED_IS_IN(ped, true)
VEHICLE.SET_DONT_PROCESS_VEHICLE_GLASS(veh, true)

That should be basically it for that kind of feature.

**Comment by Deadlineem** [comment]
Update: added this in, still figuring out where to put it though.
![Screenshot_176](https://github.com/user-attachments/assets/e7799042-2aeb-40ba-a4a4-d1df19b90157)

**Comment by rr1231234** [comment]
Thanks dude, knew this would be easily implemented
