### ISSUE TITLE
[Bug]: Can't change name of CEO or MC

### ISSUE THREAD

**Issue by BerBerOnGithub** [Deadlineem/Extras-Addon-for-YimMenu#134]
### Description

Whenever I try to change the name of CEO/MC through the menu, it changes lobby, but dosen't change name of CEO/MC

### Steps to Reproduce

1. Go to CEO/MC in Business.
2. Change name

### Version

- [X] I've confirmed the issue exists on the latest version

**Comment by Deadlineem** [comment]
I honestly have not bothered to check if this was working on 1.69 update.  Ill look into it.

**Comment by BerBerOnGithub** [comment]
Nevermind, I think it's just very buggy. Like it didn't apply after switching lobbies multiple times, then a game restart changes it.
