### ISSUE TITLE
[Bug]: hiest edittor not working

### ISSUE THREAD

**Issue by 0k1pullup** [Deadlineem/Extras-Addon-for-YimMenu#141]
### Description

As i said the heist editor wasn't working as intended , so I don't know. did i do something wrong?

### Steps to Reproduce

so what basically happened was i trying to do a heist with my friends and i followed the instructions, but it didn't work it said to them that the transaction failed and on my screen it said the heist pay was 29.9 mil for some reason i think it's a bug for the latest version of the script

### Version

- [X] I've confirmed the issue exists on the latest version

**Comment by 0k1pullup** [comment]
i was a dumbass didnt realize there was an update yesterday lol

**Comment by 0k1pullup** [comment]
nvm i updated the script but it's still aint workin
![image](https://github.com/user-attachments/assets/9a7d51ba-d978-45c8-b612-4a1ef8b71105)

**Comment by Deadlineem** [comment]
> i was a dumbass didnt realize there was an update yesterday lol

Unsure if the apartment heists are even a good idea to do at this point.  Needing to use FSL and all that posed a huge problem in recent BE updates.  I personally do not like using the apartment heists regardless, and the only one who gets them to work all the time properly is @USBMenus

**Comment by 0k1pullup** [comment]
> > i was a dumbass didnt realize there was an update yesterday lol
> 
> Unsure if the apartment heists are even a good idea to do at this point. Needing to use FSL and all that posed a huge problem in recent BE updates. I personally do not like using the apartment heists regardless, and the only one who gets them to work all the time properly is @USBMenus

I'm using fsl and all that but it's just that my friend is not getting paid

**Comment by 0k1pullup** [comment]
Well I did set it up as intended I didn't mess up with the cut and made sure it's exactly equivalent to 15mil and made sure i didn't mess up with the arrows thing and still got 30 mil for some reason, is there a method to half the 15 mil?

**Comment by Deadlineem** [comment]
> Well I did set it up as intended I didn't mess up with the cut and made sure it's exactly equivalent to 15mil and made sure i didn't mess up with the arrows thing and still got 30 mil for some reason, is there a method to half the 15 mil?

the % of the cut will say 1000% and show 15 mill, do not set it manually at all, this is what causes it to break.  refer to #122

**Comment by 0k1pullup** [comment]
> the % of the cut will say 1000% and show 15 mill, do not set it manually at all, this is what causes it to break. refer to #122

As i said i didn't do it manually i just hovered over my cut and then clicked on the 15 mil cut (made sure i didn't mess with the arrows) and i also looked into #122
as well and i followed it step by step, but it's still not working man can i send u a video to believe me?

**Comment by USBMenus** [comment]
> Well I did set it up as intended I didn't mess up with the cut and made sure it's exactly equivalent to 15mil and made sure I didn't mess up with the arrows thing and still got 30 mil for some reason, is there a method to half the 15 mil?

sounds like your changing the difficulty, you need to leave it on normal

**Comment by 0k1pullup** [comment]
> sounds like your changing the difficulty, you need to leave it on normal
>
welp apparently the apartment heists are getting doubled as some sort of event i think, so that's probably why it got doubled
and the difficulty doesn't double, it only increases 1.5 times at most 
im so so sorry for wasting your time im such a dummy

**Comment by Deadlineem** [comment]
> > sounds like your changing the difficulty, you need to leave it on normal
> 
> welp apparently the apartment heists are getting doubled as some sort of event i think, so that's probably why it got doubled and the difficulty doesn't double, it only increases 1.5 times at most im so so sorry for wasting your time im such a dummy

I was not aware that the apartment heists went double this week, that would make perfect sense as to why its going to 30 million.  I'm going to see if there is a way to detect such events and if the event is active, decrease the total payout to 7.5mill (15 mill with double event) which would solve the issue.  Or just wait until the double events are over.
