### ISSUE TITLE
Clown Jet Attack error

### ISSUE THREAD

**Issue by DayibBaba** [Deadlineem/Extras-Addon-for-YimMenu#22]
Enabling the Clown Jet Attack checkbox under the 'Global' menu gives the following error:
`[FATAL/lua_module.cpp:80FATAL/] lua_manager.cpp:335] \..\scripts\Extras-Addon.lua:5228: attempt to call a nil value (method 'yield')
stack traceback:
        .YimMenu\scripts\Extras-Addon.lua:5228: in function <scripts\Extras-Addon.lua:5205>
Extras-Addon.lua: ...sRoaming\YimMenu\scripts\Extras-Addon.lua:5228: attempt to call a nil value (method 'yield')
stack traceback:
        scripts\Extras-Addon.lua:5228: in function <...sscripts\Extras-Addon.lua:5205>`

**Comment by Deadlineem** [comment]
due to clownJetAttack:yield()  not being able to yield the function bc its not defined i assume.  pushed a quick commit @DayibBaba can you lmk if this persists?

#https://github.com/Deadlineem/Extras-Addon-for-YimMenu/commit/dcbb3b2d665c20ac24ac322f77dc5269945854e7

**Comment by Deadlineem** [comment]
Issue seems to be fixed, I will keep this opened just in case you still have issues.

https://github.com/Deadlineem/Extras-Addon-for-YimMenu/commit/8b12ef8ab697b0f124f10c8f748ce900ec174d7d
