### ISSUE TITLE
Script doesn't load

### ISSUE THREAD

**Issue by darkwanderr** [Deadlineem/Extras-Addon-for-YimMenu#33]
It doesn't load into yimmenu.

_Here is the log:_

```
[14:30:57.6794497][FATAL/lua_module.cpp:264] Extras-Addon.lua tried calling a currently not supported lua function: package.searcher C
[14:30:57.6802782][FATAL/lua_module.cpp:264] Extras-Addon.lua tried calling a currently not supported lua function: package.searcher Croot
[14:30:57.6813801][FATAL/lua_module.cpp:80] ...s\space\AppData\Roaming\YimMenu\scripts\Extras-Addon.lua:1: module 'json' not found:
        no field package.preload['json']
        no file 'C:\Users\space\AppData\Roaming\YimMenu\scripts/json.lua'
        no file 'C:\Users\space\AppData\Roaming\YimMenu\scripts\disabled/json.lua'
stack traceback:
        [C]: in function 'base.require'
        ...s\space\AppData\Roaming\YimMenu\scripts\Extras-Addon.lua:1: in main chunk
[14:30:57.6819834][FATAL/lua_module.cpp:325] Extras-Addon.lua failed to load: ...s\space\AppData\Roaming\YimMenu\scripts\Extras-Addon.lua:1: module 'json' not found:
        no field package.preload['json']
        no file 'C:\Users\space\AppData\Roaming\YimMenu\scripts/json.lua'
        no file 'C:\Users\space\AppData\Roaming\YimMenu\scripts\disabled/json.lua'
stack traceback:
        [C]: in function 'base.require'
        ...s\space\AppData\Roaming\YimMenu\scripts\Extras-Addon.lua:1: in main chunk
```

**Comment by Deadlineem** [comment]
Pretty sure this has something to do with the config file additions we were attempting last night.  I have forwarded this to @USBMenus for a solution as this is one of the things he was working on last night.

Thank you for letting us know!

**Comment by Deadlineem** [comment]
@darkwanderr try downloading it now and using it, let me know how it works.  I just commented out the config file portions until hes around to resolve it.

**Comment by USBMenus** [comment]
pushed the fix, should work now

**Comment by darkwanderr** [comment]
> @darkwanderr try downloading it now and using it, let me know how it works. I just commented out the config file portions until hes around to resolve it.

Yeah works fine now.

**Comment by USBMenus** [comment]
> > @darkwanderr try downloading it now and using it, let me know how it works. I just commented out the config file portions until hes around to resolve it.
> 
> Yeah works fine now.

updated it again so the config should work properly, please let me know

**Comment by darkwanderr** [comment]
> > > @darkwanderr try downloading it now and using it, let me know how it works. I just commented out the config file portions until hes around to resolve it.
> > 
> > 
> > Yeah works fine now.
> 
> updated it again so the config should work properly, please let me know

Doesn't work now, I attached the error logs below.

### _**Log 1:**_
```
[17:09:09.9575890][FATAL/lua_module.cpp:264] Extras-Addon (10).lua tried calling a currently not supported lua function: package.searcher C
[17:09:09.9576781][FATAL/lua_module.cpp:264] Extras-Addon (10).lua tried calling a currently not supported lua function: package.searcher Croot
[17:09:09.9581861][FATAL/lua_module.cpp:80] ...ce\AppData\Roaming\YimMenu\scripts\Extras-Addon (10).lua:1: module 'json' not found:
	no field package.preload['json']
	no file 'C:\Users\space\AppData\Roaming\YimMenu\scripts/json.lua'
	no file 'C:\Users\space\AppData\Roaming\YimMenu\scripts\disabled/json.lua'
stack traceback:
	[C]: in function 'base.require'
	...ju\AppData\Roaming\YimMenu\scripts\Extras-Addon (10).lua:1: in main chunk
[17:09:09.9588892][FATAL/lua_module.cpp:325] Extras-Addon (10).lua failed to load: ...ce\AppData\Roaming\YimMenu\scripts\Extras-Addon (10).lua:1: module 'json' not found:
	no field package.preload['json']
	no file 'C:\Users\space\AppData\Roaming\YimMenu\scripts/json.lua'
	no file 'C:\Users\space\AppData\Roaming\YimMenu\scripts\disabled/json.lua'
stack traceback:
	[C]: in function 'base.require'
	...ju\AppData\Roaming\YimMenu\scripts\Extras-Addon (10).lua:1: in main chunk
[17:09:09.9754290][INFO/lua_module.cpp:330] Loaded YimActions.lua
[17:09:42.3084194][WARN/lua_manager.cpp:240] C:\Users\space\AppData\Roaming\YimMenu\scripts\Extras-Addon (10).lua does not exist in the filesystem. Not loading it.
```




### **_Log 2:_**
```
[17:09:48.8781472][FATAL/lua_module.cpp:264] Extras-Addon.lua tried calling a currently not supported lua function: package.searcher C
[17:09:48.8782510][FATAL/lua_module.cpp:264] Extras-Addon.lua tried calling a currently not supported lua function: package.searcher Croot
[17:09:48.8783676][FATAL/lua_module.cpp:80] ...s\space\AppData\Roaming\YimMenu\scripts\Extras-Addon.lua:1: module 'json' not found:
	no field package.preload['json']
	no file 'C:\Users\space\AppData\Roaming\YimMenu\scripts/json.lua'
	no file 'C:\Users\space\AppData\Roaming\YimMenu\scripts\disabled/json.lua'
stack traceback:
	[C]: in function 'base.require'
	...s\space\AppData\Roaming\YimMenu\scripts\Extras-Addon.lua:1: in main chunk
[17:09:48.8784018][FATAL/lua_module.cpp:325] Extras-Addon.lua failed to load: ...s\space\AppData\Roaming\YimMenu\scripts\Extras-Addon.lua:1: module 'json' not found:
	no field package.preload['json']
	no file 'C:\Users\space\AppData\Roaming\YimMenu\scripts/json.lua'
	no file 'C:\Users\space\AppData\Roaming\YimMenu\scripts\disabled/json.lua'
stack traceback:
	[C]: in function 'base.require'
	...s\space\AppData\Roaming\YimMenu\scripts\Extras-Addon.lua:1: in main chunk
```

**Comment by USBMenus** [comment]
> > > > @darkwanderr try downloading it now and using it, let me know how it works. I just commented out the config file portions until hes around to resolve it.
> > > 
> > > 
> > > Yeah works fine now.
> > 
> > 
> > updated it again so the config should work properly, please let me know
> 
> Doesn't work now, I attached the error logs below.
> 
> ### _**Log 1:**_
> ```
> [17:09:09.9575890][FATAL/lua_module.cpp:264] Extras-Addon (10).lua tried calling a currently not supported lua function: package.searcher C
> [17:09:09.9576781][FATAL/lua_module.cpp:264] Extras-Addon (10).lua tried calling a currently not supported lua function: package.searcher Croot
> [17:09:09.9581861][FATAL/lua_module.cpp:80] ...ce\AppData\Roaming\YimMenu\scripts\Extras-Addon (10).lua:1: module 'json' not found:
> 	no field package.preload['json']
> 	no file 'C:\Users\space\AppData\Roaming\YimMenu\scripts/json.lua'
> 	no file 'C:\Users\space\AppData\Roaming\YimMenu\scripts\disabled/json.lua'
> stack traceback:
> 	[C]: in function 'base.require'
> 	...ce\AppData\Roaming\YimMenu\scripts\Extras-Addon (10).lua:1: in main chunk
> [17:09:09.9588892][FATAL/lua_module.cpp:325] Extras-Addon (10).lua failed to load: ...ce\AppData\Roaming\YimMenu\scripts\Extras-Addon (10).lua:1: module 'json' not found:
> 	no field package.preload['json']
> 	no file 'C:\Users\space\AppData\Roaming\YimMenu\scripts/json.lua'
> 	no file 'C:\Users\space\AppData\Roaming\YimMenu\scripts\disabled/json.lua'
> stack traceback:
> 	[C]: in function 'base.require'
> 	...ce\AppData\Roaming\YimMenu\scripts\Extras-Addon (10).lua:1: in main chunk
> [17:09:09.9754290][INFO/lua_module.cpp:330] Loaded YimActions.lua
> [17:09:42.3084194][WARN/lua_manager.cpp:240] C:\Users\space\AppData\Roaming\YimMenu\scripts\Extras-Addon (10).lua does not exist in the filesystem. Not loading it.
> ```
> 
> ### **_Log 2:_**
> ```
> [17:09:48.8781472][FATAL/lua_module.cpp:264] Extras-Addon.lua tried calling a currently not supported lua function: package.searcher C
> [17:09:48.8782510][FATAL/lua_module.cpp:264] Extras-Addon.lua tried calling a currently not supported lua function: package.searcher Croot
> [17:09:48.8783676][FATAL/lua_module.cpp:80] ...s\space\AppData\Roaming\YimMenu\scripts\Extras-Addon.lua:1: module 'json' not found:
> 	no field package.preload['json']
> 	no file 'C:\Users\space\AppData\Roaming\YimMenu\scripts/json.lua'
> 	no file 'C:\Users\space\AppData\Roaming\YimMenu\scripts\disabled/json.lua'
> stack traceback:
> 	[C]: in function 'base.require'
> 	...s\space\AppData\Roaming\YimMenu\scripts\Extras-Addon.lua:1: in main chunk
> [17:09:48.8784018][FATAL/lua_module.cpp:325] Extras-Addon.lua failed to load: ...s\space\AppData\Roaming\YimMenu\scripts\Extras-Addon.lua:1: module 'json' not found:
> 	no field package.preload['json']
> 	no file 'C:\Users\space\AppData\Roaming\YimMenu\scripts/json.lua'
> 	no file 'C:\Users\space\AppData\Roaming\YimMenu\scripts\disabled/json.lua'
> stack traceback:
> 	[C]: in function 'base.require'
> 	...s\space\AppData\Roaming\YimMenu\scripts\Extras-Addon.lua:1: in main chunk
> ```

did you update it? you need the json.lua, you can either download it from the github, or update the script with the update.bat

**Comment by darkwanderr** [comment]
> > > > > @darkwanderr try downloading it now and using it, let me know how it works. I just commented out the config file portions until hes around to resolve it.
> > > > 
> > > > 
> > > > Yeah works fine now.
> > > 
> > > 
> > > updated it again so the config should work properly, please let me know
> > 
> > 
> > Doesn't work now, I attached the error logs below.
> > ### _**Log 1:**_
> > ```
> > [17:09:09.9575890][FATAL/lua_module.cpp:264] Extras-Addon (10).lua tried calling a currently not supported lua function: package.searcher C
> > [17:09:09.9576781][FATAL/lua_module.cpp:264] Extras-Addon (10).lua tried calling a currently not supported lua function: package.searcher Croot
> > [17:09:09.9581861][FATAL/lua_module.cpp:80] ...ce\AppData\Roaming\YimMenu\scripts\Extras-Addon (10).lua:1: module 'json' not found:
> > 	no field package.preload['json']
> > 	no file 'C:\Users\space\AppData\Roaming\YimMenu\scripts/json.lua'
> > 	no file 'C:\Users\space\AppData\Roaming\YimMenu\scripts\disabled/json.lua'
> > stack traceback:
> > 	[C]: in function 'base.require'
> > 	...ce\AppData\Roaming\YimMenu\scripts\Extras-Addon (10).lua:1: in main chunk
> > [17:09:09.9588892][FATAL/lua_module.cpp:325] Extras-Addon (10).lua failed to load: ...ce\AppData\Roaming\YimMenu\scripts\Extras-Addon (10).lua:1: module 'json' not found:
> > 	no field package.preload['json']
> > 	no file 'C:\Users\space\AppData\Roaming\YimMenu\scripts/json.lua'
> > 	no file 'C:\Users\space\AppData\Roaming\YimMenu\scripts\disabled/json.lua'
> > stack traceback:
> > 	[C]: in function 'base.require'
> > 	...ce\AppData\Roaming\YimMenu\scripts\Extras-Addon (10).lua:1: in main chunk
> > [17:09:09.9754290][INFO/lua_module.cpp:330] Loaded YimActions.lua
> > [17:09:42.3084194][WARN/lua_manager.cpp:240] C:\Users\space\AppData\Roaming\YimMenu\scripts\Extras-Addon (10).lua does not exist in the filesystem. Not loading it.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### **_Log 2:_**
> > ```
> > [17:09:48.8781472][FATAL/lua_module.cpp:264] Extras-Addon.lua tried calling a currently not supported lua function: package.searcher C
> > [17:09:48.8782510][FATAL/lua_module.cpp:264] Extras-Addon.lua tried calling a currently not supported lua function: package.searcher Croot
> > [17:09:48.8783676][FATAL/lua_module.cpp:80] ...s\space\AppData\Roaming\YimMenu\scripts\Extras-Addon.lua:1: module 'json' not found:
> > 	no field package.preload['json']
> > 	no file 'C:\Users\space\AppData\Roaming\YimMenu\scripts/json.lua'
> > 	no file 'C:\Users\space\AppData\Roaming\YimMenu\scripts\disabled/json.lua'
> > stack traceback:
> > 	[C]: in function 'base.require'
> > 	...s\space\AppData\Roaming\YimMenu\scripts\Extras-Addon.lua:1: in main chunk
> > [17:09:48.8784018][FATAL/lua_module.cpp:325] Extras-Addon.lua failed to load: ...s\space\AppData\Roaming\YimMenu\scripts\Extras-Addon.lua:1: module 'json' not found:
> > 	no field package.preload['json']
> > 	no file 'C:\Users\space\AppData\Roaming\YimMenu\scripts/json.lua'
> > 	no file 'C:\Users\space\AppData\Roaming\YimMenu\scripts\disabled/json.lua'
> > stack traceback:
> > 	[C]: in function 'base.require'
> > 	...s\space\AppData\Roaming\YimMenu\scripts\Extras-Addon.lua:1: in main chunk
> > ```
> 
> did you update it? you need the json.lua, you can either download it from the github, or update the script with the update.bat

I updated it, now working.

This popped up in the console log if it's anything important
`[19:03:17.3985509][WARN/lua_module.cpp:233] Couldn't io.open a file called Extras-Addon.json mode (r). Note that io.open is restricted to the scripts_config folder. If you want to check if a file exists, use io.exists`

**Comment by USBMenus** [comment]
the warning just lets the user know the file doesnt exist, it creates it if there isnt one

**Comment by matigasnatite** [comment]
[04:41:52.5390362][FATAL/lua_module.cpp:264] Extras-Addon.lua tried calling a currently not supported lua function: package.searcher C
[04:41:52.5395209][FATAL/lua_module.cpp:264] Extras-Addon.lua tried calling a currently not supported lua function: package.searcher Croot
[04:41:52.5400575][FATAL/lua_module.cpp:80] ...rs\deco\AppData\Roaming\YimMenu\scripts\Extras-Addon.lua:1: module 'json' not found:
        no field package.preload['json']
        no file 'C:\Users\deco\AppData\Roaming\YimMenu\scripts/json.lua'
        no file 'C:\Users\deco\AppData\Roaming\YimMenu\scripts\disabled/json.lua'
stack traceback:
        [C]: in function 'base.require'
        ...rs\deco\AppData\Roaming\YimMenu\scripts\Extras-Addon.lua:1: in main chunk
[04:41:52.5400767][FATAL/lua_module.cpp:325] Extras-Addon.lua failed to load: ...rs\deco\AppData\Roaming\YimMenu\scripts\Extras-Addon.lua:1: module 'json' not found:
        no field package.preload['json']
        no file 'C:\Users\deco\AppData\Roaming\YimMenu\scripts/json.lua'
        no file 'C:\Users\deco\AppData\Roaming\YimMenu\scripts\disabled/json.lua'
stack traceback:
        [C]: in function 'base.require'
        ...rs\deco\AppData\Roaming\YimMenu\scripts\Extras-Addon.lua:1: in main chunk
[04:41:55.2312729][FATAL/lua_module.cpp:264] Extras-Addon.lua tried calling a currently not supported lua function: package.searcher C
[04:41:55.2316450][FATAL/lua_module.cpp:264] Extras-Addon.lua tried calling a currently not supported lua function: package.searcher Croot
[04:41:55.2322272][FATAL/lua_module.cpp:80] ...rs\deco\AppData\Roaming\YimMenu\scripts\Extras-Addon.lua:1: module 'json' not found:
        no field package.preload['json']
        no file 'C:\Users\deco\AppData\Roaming\YimMenu\scripts/json.lua'
        no file 'C:\Users\deco\AppData\Roaming\YimMenu\scripts\disabled/json.lua'
stack traceback:
        [C]: in function 'base.require'
        ...rs\deco\AppData\Roaming\YimMenu\scripts\Extras-Addon.lua:1: in main chunk
[04:41:55.2322511][FATAL/lua_module.cpp:325] Extras-Addon.lua failed to load: ...rs\deco\AppData\Roaming\YimMenu\scripts\Extras-Addon.lua:1: module 'json' not found:

**Comment by matigasnatite** [comment]
how can i fix this guys, anyone?

**Comment by Deadlineem** [comment]
> how can i fix this guys, anyone?

You need to open the lua scripts folder and check to make sure you have Extras-Addon.lua, Extras-data.lua and json.lua, if you do not have these, download them manually or use the update.bat file to update them by running it and pressing 1 then Y and hitting enter, be sure to have the latest version of the update.bat if you are doing it this way.
