### ISSUE TITLE
The latest lua file is abnormal and does not work in YimMenu. The previous version was normal.

### ISSUE THREAD

**Issue by USERNyZa** [Deadlineem/Extras-Addon-for-YimMenu#38]

**Comment by USERNyZa** [comment]
![A`[I$ZIV4JE26GS6HYZ7_}B(1).png](https://github.com/Deadlineem/Extras-Addon-for-YimMenu/assets/53617247/f3965ffc-8374-4eba-a5fb-72fd3806871f)

**Comment by Deadlineem** [comment]
https://github.com/Deadlineem/Extras-Addon-for-YimMenu/issues/33

See the issue above.  You need to update the update.bat file, open it and press 1, Y, [Enter]

this will now download a json.lua file into the scripts folder as well.
