### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by A5m0deu5** [Deadlineem/Extras-Addon-for-YimMenu#44]
When i wanna use some drops or car gifts after some time being in a session - game is crashing. It mostly works normally if i don't use any Yim or Extras Addon's features first.

[cout.log](https://github.com/Deadlineem/Extras-Addon-for-YimMenu/files/14765569/cout.log)

**Comment by Deadlineem** [comment]
Its most likely an overload to the script from using a bunch of options, not sure what its related to as the cout.log doesn't have info related to the extras addon lua in there 

[23:34:22.5072893][FATAL/lua_module.cpp:80] An unknown error has triggered the error handler
stack traceback:
[23:34:22.5083117][FATAL/lua_module.cpp:57] error message: An unknown error has triggered the error handler
stack traceback:
[23:34:22.5083057][FATAL/lua_module.cpp:53] Lua is in a panic state and will now abort() the application

**Comment by A5m0deu5** [comment]
> Its most likely an overload to the script from using a bunch of options, not sure what its related to as the cout.log doesn't have info related to the extras addon lua in there
> 
> [23:34:22.5072893][FATAL/lua_module.cpp:80] An unknown error has triggered the error handler stack traceback: [23:34:22.5083117][FATAL/lua_module.cpp:57] error message: An unknown error has triggered the error handler stack traceback: [23:34:22.5083057][FATAL/lua_module.cpp:53] Lua is in a panic state and will now abort() the application

I'll do some tests today tryin reproduce a crash and update the log.. or logs :D Ty 4 info
