### ISSUE TITLE
Crashes when enabling PR Crash too long

### ISSUE THREAD

**Issue by AhmadToamah2010** [Deadlineem/Extras-Addon-for-YimMenu#45]
cout.txt error codes:
[12:22:02.9657632][WARN/log_message_error_box.cpp:37] Error Code: Fatal Error
[12:22:02.9715758][FATAL/log_message_error_box.cpp:14] EXCEPTION_ACCESS_VIOLATION
Dumping modules:
GTA5.exe Base Address: 0x7FF6C77A0000 Size: 67215872
ntdll.dll Base Address: 0x7FF8DDAB0000 Size: 1153536
KERNEL32.DLL Base Address: 0x7FF8DD8B0000 Size: 513536
KERNELBASE.dll Base Address: 0x7FF8DB6B0000 Size: 1255936
apphelp.dll Base Address: 0x7FF8D89C0000 Size: 323584
AcLayers.DLL Base Address: 0x7FF8BB220000 Size: 175104
msvcrt.dll Base Address: 0x7FF8DCE40000 Size: 477184
USER32.dll Base Address: 0x7FF8DD590000 Size: 584704
win32u.dll Base Address: 0x7FF8DB680000 Size: 42496
GDI32.dll Base Address: 0x7FF8DCEE0000 Size: 61952
gdi32full.dll Base Address: 0x7FF8DB270000 Size: 686080
msvcp_win.dll Base Address: 0x7FF8DB4B0000 Size: 344064
ucrtbase.dll Base Address: 0x7FF8DB550000 Size: 735744
SHELL32.dll Base Address: 0x7FF8DC130000 Size: 5804544
SHLWAPI.dll Base Address: 0x7FF8DBE00000 Size: 182784
ADVAPI32.dll Base Address: 0x7FF8DCF10000 Size: 423424
sechost.dll Base Address: 0x7FF8DD7B0000 Size: 412672
RPCRT4.dll Base Address: 0x7FF8DBF10000 Size: 923136
sfc.dll Base Address: 0x22D81890000 Size: 0
WINSPOOL.DRV Base Address: 0x7FF8C5B50000 Size: 364544
combase.dll Base Address: 0x7FF8DD210000 Size: 2327040
shcore.dll Base Address: 0x7FF8DBE60000 Size: 476672
sfc_os.DLL Base Address: 0x7FF8D4BB0000 Size: 28672
AcGenral.DLL Base Address: 0x7FF8C7E40000 Size: 243200
ole32.dll Base Address: 0x7FF8DCFC0000 Size: 832000
USERENV.dll Base Address: 0x7FF8DB040000 Size: 108032
MPR.dll Base Address: 0x7FF8C2290000 Size: 71168
SspiCli.dll Base Address: 0x7FF8DB070000 Size: 123904
IMM32.DLL Base Address: 0x7FF8DD970000 Size: 122368
PSAPI.DLL Base Address: 0x7FF8DD580000 Size: 2048
WS2_32.dll Base Address: 0x7FF8DDA00000 Size: 275456
CRYPT32.dll Base Address: 0x7FF8DB9B0000 Size: 1100288
GFSDK_ShadowLib.win64.dll Base Address: 0x7FF886070000 Size: 96256
VERSION.dll Base Address: 0x7FF8D5F90000 Size: 10752
WINTRUST.dll Base Address: 0x7FF8DB390000 Size: 292864
DSOUND.dll Base Address: 0x7FF8BA700000 Size: 380928
bink2w64.dll Base Address: 0x7FF8BA670000 Size: 307712
bcrypt.dll Base Address: 0x7FF8DB650000 Size: 102912
OLEAUT32.dll Base Address: 0x7FF8DCD70000 Size: 608768
WININET.dll Base Address: 0x7FF8C3A50000 Size: 2019840
WINMM.dll Base Address: 0x7FF8CE2C0000 Size: 81408
MF.dll Base Address: 0x7FF8AAFD0000 Size: 340992
MFPlat.DLL Base Address: 0x7FF8BBDF0000 Size: 1409536
msdmo.dll Base Address: 0x7FF8D64C0000 Size: 13312
cfgmgr32.dll Base Address: 0x7FF8DB220000 Size: 219136
MFReadWrite.dll Base Address: 0x7FF8A3630000 Size: 918016
PROPSYS.dll Base Address: 0x7FF8D6B00000 Size: 631296
WTSAPI32.dll Base Address: 0x7FF8D6E20000 Size: 37888
d3d9.dll Base Address: 0x7FF8B5EB0000 Size: 1371648
D3DCOMPILER_43.dll Base Address: 0x7FF8B5B80000 Size: 2423296
GFSDK_TXAA_AlphaResolve.win64.dll Base Address: 0x7FF8C2BB0000 Size: 48128
DINPUT8.dll Base Address: 0x7FF8C2D20000 Size: 169472
XINPUT1_3.dll Base Address: 0x400000 Size: 85504
SETUPAPI.dll Base Address: 0x7FF8DC900000 Size: 887808
IPHLPAPI.DLL Base Address: 0x7FF8DA550000 Size: 166400
powrprof.dll Base Address: 0x7FF8DAD30000 Size: 70656
winmmbase.dll Base Address: 0x7FF8B94D0000 Size: 95232
kernel.appcore.dll Base Address: 0x7FF8D8F30000 Size: 16384
dwmapi.dll Base Address: 0x7FF8D8FA0000 Size: 99328
windows.storage.dll Base Address: 0x7FF8D9240000 Size: 5841408
Wldp.dll Base Address: 0x7FF8DAB00000 Size: 94720
MFCORE.DLL Base Address: 0x7FF885BE0000 Size: 3959296
ksuser.dll Base Address: 0x7FF8D4B70000 Size: 6144
CRYPTBASE.DLL Base Address: 0x7FF8DAA50000 Size: 10752
d3dx9_43.dll Base Address: 0x7FF885970000 Size: 2280960
OPENGL32.dll Base Address: 0x7FF8B5A50000 Size: 909312
GLU32.dll Base Address: 0x7FF8C27E0000 Size: 122880
UMPDC.dll Base Address: 0x7FF8DAD10000 Size: 34816
bcryptPrimitives.dll Base Address: 0x7FF8DB190000 Size: 408576
RTWorkQ.DLL Base Address: 0x7FF8BBDB0000 Size: 105472
MSASN1.dll Base Address: 0x7FF8DACF0000 Size: 34816
inputhost.dll Base Address: 0x7FF8D2310000 Size: 976384
wintypes.dll Base Address: 0x7FF8D7C20000 Size: 487424
CoreMessaging.dll Base Address: 0x7FF8D8650000 Size: 606720
CoreUIComponents.dll Base Address: 0x7FF8D82F0000 Size: 1804800
ntmarta.dll Base Address: 0x7FF8DA200000 Size: 140288
dbghelp.dll Base Address: 0x7FF8CD6C0000 Size: 1400320
dbgcore.DLL Base Address: 0x7FF8C7C60000 Size: 136704
d3d12.dll Base Address: 0x7FF8BB800000 Size: 92160
CRYPTSP.dll Base Address: 0x7FF8DAA60000 Size: 46080
uxtheme.dll Base Address: 0x7FF8D8B70000 Size: 382976
rsaenh.dll Base Address: 0x7FF8DA170000 Size: 142336
clbcatq.dll Base Address: 0x7FF8DBBA0000 Size: 437760
EOSSDK-Win64-Shipping.dll Base Address: 0x7FF884F50000 Size: 7229440
WLDAP32.dll Base Address: 0x7FF8DD850000 Size: 240128
Normaliz.dll Base Address: 0x7FF8DD570000 Size: 512
WINHTTP.dll Base Address: 0x7FF8D5650000 Size: 845312
Secur32.dll Base Address: 0x7FF8C31E0000 Size: 11264
VCRUNTIME140.dll Base Address: 0x7FF8D4C60000 Size: 65024
MSVCP140.dll Base Address: 0x7FF8C4230000 Size: 345600
VCRUNTIME140_1.dll Base Address: 0x7FF8D4BA0000 Size: 15360
dxdiagn.dll Base Address: 0x7FF8B63D0000 Size: 395264
dxgi.dll Base Address: 0x7FF8D9A20000 Size: 614912
DEVOBJ.dll Base Address: 0x7FF8DAF20000 Size: 132608
d3d11.dll Base Address: 0x7FF8D72A0000 Size: 1853440
WMICLNT.dll Base Address: 0x7FF8D6550000 Size: 31744
wbemprox.dll Base Address: 0x7FF8C76B0000 Size: 27648
wbemcomn.dll Base Address: 0x7FF8C7F80000 Size: 328704
wbemsvc.dll Base Address: 0x7FF8C5A60000 Size: 7168
fastprox.dll Base Address: 0x7FF8C62F0000 Size: 708608
amsi.dll Base Address: 0x7FF8C5210000 Size: 62464
NSI.dll Base Address: 0x7FF8DC120000 Size: 7680
dhcpcsvc6.DLL Base Address: 0x7FF8D5FF0000 Size: 23552
dhcpcsvc.DLL Base Address: 0x7FF8D5FD0000 Size: 61440
mswsock.dll Base Address: 0x7FF8DA860000 Size: 331776
napinsp.dll Base Address: 0x7FF8C7EC0000 Size: 50176
pnrpnsp.dll Base Address: 0x7FF8C7E20000 Size: 66048
wshbth.dll Base Address: 0x7FF8C7E00000 Size: 43008
NLAapi.dll Base Address: 0x7FF8D6C80000 Size: 68608
DNSAPI.dll Base Address: 0x7FF8DA590000 Size: 595456
winrnr.dll Base Address: 0x7FF8C7DE0000 Size: 32768
nvapi64.dll Base Address: 0x7FF8C8AF0000 Size: 5632000
cryptnet.dll Base Address: 0x7FF8D5040000 Size: 135168
drvstore.dll Base Address: 0x7FF8D4E40000 Size: 979456
D3D10_1.DLL Base Address: 0x7FF8BACC0000 Size: 130048
d3d10_1core.dll Base Address: 0x7FF8C7EB0000 Size: 7680
imagehlp.dll Base Address: 0x7FF8DC880000 Size: 45056
profapi.dll Base Address: 0x7FF8DB0C0000 Size: 88064
MSCTF.dll Base Address: 0x7FF8DD0F0000 Size: 864256
textinputframework.dll Base Address: 0x7FF8D2470000 Size: 726016
WINSTA.dll Base Address: 0x7FF8DAB30000 Size: 190976
nvldumdx.dll Base Address: 0x7FF8D2AB0000 Size: 599040
rasadhlp.dll Base Address: 0x7FF8D5080000 Size: 7168
nvgpucomp64.dll Base Address: 0x7FF8D00F0000 Size: 29258752
NvMessageBus.dll Base Address: 0x7FF8C76D0000 Size: 2750976
nvwgf2umx.dll Base Address: 0x7FF8C9370000 Size: 20640768
dxcore.dll Base Address: 0x7FF8D2F20000 Size: 147968
fwpuclnt.dll Base Address: 0x7FF8D48D0000 Size: 288768
HID.DLL Base Address: 0x7FF8D99E0000 Size: 20480
MMDevApi.dll Base Address: 0x7FF8D4BD0000 Size: 387072
XAudio2_7.dll Base Address: 0x7FF8A59F0000 Size: 485376
AUDIOSES.DLL Base Address: 0x7FF8C0C10000 Size: 1037312
resourcepolicyclient.dll Base Address: 0x7FF8D8C30000 Size: 31744
Windows.UI.dll Base Address: 0x7FF8D2960000 Size: 731136
WindowManagementAPI.dll Base Address: 0x7FF8D5760000 Size: 450048
twinapi.appcore.dll Base Address: 0x7FF8D5440000 Size: 1468416
avrt.dll Base Address: 0x7FF8D5FB0000 Size: 5632
gpapi.dll Base Address: 0x7FF8D99F0000 Size: 69120
WINNSI.DLL Base Address: 0x7FF8D6010000 Size: 11776
socialclub.dll Base Address: 0x7FF8A7B10000 Size: 2692608
chrome_elf.dll Base Address: 0x7FF8BAFB0000 Size: 901120
libcef.dll Base Address: 0x7FF886E60000 Size: 151009280
COMDLG32.dll Base Address: 0x7FF8DC040000 Size: 684032
COMCTL32.dll Base Address: 0x7FF8C4F30000 Size: 560128
UIAutomationCore.DLL Base Address: 0x7FF8BA1C0000 Size: 2040832
OLEACC.dll Base Address: 0x7FF8C5AE0000 Size: 260608
NETAPI32.dll Base Address: 0x7FF8BE810000 Size: 47616
DWrite.dll Base Address: 0x7FF8C6EF0000 Size: 1601024
ncrypt.dll Base Address: 0x7FF8DABD0000 Size: 102400
USP10.dll Base Address: 0x7FF8C31F0000 Size: 512
urlmon.dll Base Address: 0x7FF8C8900000 Size: 1282560
dxva2.dll Base Address: 0x7FF8B9190000 Size: 96256
wevtapi.dll Base Address: 0x7FF8D6450000 Size: 296960
CRYPTUI.dll Base Address: 0x7FF8B5E30000 Size: 246272
credui.dll Base Address: 0x7FF8B5E90000 Size: 61952
ESENT.dll Base Address: 0x7FF8C48D0000 Size: 2585088
iertutil.dll Base Address: 0x7FF8CE000000 Size: 550400
srvcli.dll Base Address: 0x7FF8C82F0000 Size: 58368
netutils.dll Base Address: 0x7FF8DA660000 Size: 19456
DSROLE.DLL Base Address: 0x7FF8D6AF0000 Size: 7680
WKSCLI.DLL Base Address: 0x7FF8DA2D0000 Size: 51200
SAMCLI.DLL Base Address: 0x7FF8C7690000 Size: 61440
NTASN1.dll Base Address: 0x7FF8DAB90000 Size: 81408
FirewallAPI.dll Base Address: 0x7FF8D9D80000 Size: 364544
fwbase.dll Base Address: 0x7FF8D9D10000 Size: 159744
FWPolicyIOMgr.dll Base Address: 0x7FF8C5A80000 Size: 216064
wdmaud.drv Base Address: 0x7FF8A42F0000 Size: 193024
msacm32.drv Base Address: 0x7FF8C43B0000 Size: 17920
MSACM32.dll Base Address: 0x7FF8D4E20000 Size: 74240
midimap.dll Base Address: 0x7FF8C4080000 Size: 13312
ondemandconnroutehelper.dll Base Address: 0x7FF8D3130000 Size: 42496
YimMenu.dll Base Address: 0x7FF8A8350000 Size: 8016896
MSVCP140_2.dll Base Address: 0x7FF8BB830000 Size: 197632
D3DCOMPILER_47.dll Base Address: 0x7FF8D6E40000 Size: 3396608
winbrand.dll Base Address: 0x7FF8C4C50000 Size: 161792
xinput1_4.dll Base Address: 0x7FF8D60B0000 Size: 30208
schannel.DLL Base Address: 0x7FF8DA080000 Size: 480768
mskeyprotect.dll Base Address: 0x7FF8C22B0000 Size: 48640
ncryptsslp.dll Base Address: 0x7FF8C2360000 Size: 78848
Dumping registers:
RAX: 0x1
RCX: 0xF571D4109EEB0000
RDX: 0xF
RBX: 0x42C098EFE0
RSI: 0xE4FFFFFF
RDI: 0x42C098F028
RSP: 0x42C098EF70
RBP: 0x42C098F1D1
R8:  0x22D81870D80
R9:  0x1
R10: 0x8000
R11: 0x42C098EE40
R12: 0x1
R13: 0x42C098F508
R14: 0x0
R15: 0x4000000
Dumping stacktrace:
[0]	YimMenu.dll+0x1869E4 0x7FF8A84D69E4
[1]	YimMenu.dll+0x186B1B 0x7FF8A84D6B1B
[2]	GTA5.exe+0x1323AB7 0x7FF6C8AC3AB7
[3]	GTA5.exe+0x6BBF39 0x7FF6C7E5BF39
[4]	GTA5.exe+0xCFD516 0x7FF6C849D516
[5]	GTA5.exe+0xCD74FB 0x7FF6C84774FB
[6]	GTA5.exe+0xCC56F1 0x7FF6C84656F1
[7]	YimMenu.dll+0x3D4374 0x7FF8A8724374
[8]	YimMenu.dll+0x3DCF55 0x7FF8A872CF55
[9]	YimMenu.dll+0x3DC2BE 0x7FF8A872C2BE
[10]	YimMenu.dll+0x1B238B 0x7FF8A850238B
[11]	YimMenu.dll+0x6E910A 0x7FF8A8A3910A
[12]	YimMenu.dll+0x6E8565 0x7FF8A8A38565
[13]	YimMenu.dll+0x6FFF62 0x7FF8A8A4FF62
[14]	YimMenu.dll+0x6E7C82 0x7FF8A8A37C82
[15]	YimMenu.dll+0x6E88C3 0x7FF8A8A388C3
[16]	YimMenu.dll+0x6E8D9E 0x7FF8A8A38D9E
[17]	YimMenu.dll+0x23BC12 0x7FF8A858BC12
[18]	YimMenu.dll+0x23A34F 0x7FF8A858A34F
[19]	YimMenu.dll+0x49754F 0x7FF8A87E754F
[20]	YimMenu.dll+0x49727C 0x7FF8A87E727C
[21]	YimMenu.dll+0x49728C 0x7FF8A87E728C
[22]	KERNELBASE.dll PackageIdFromFullName
[23]	ntdll.dll RtlUserFiberStart
--------End of exception--------

**Comment by Deadlineem** [comment]
Since this is just an addon, we cannot determine the exact cause of the crash via cout.log, however, I will assume its due to how the PR crash works.

What this does is, it spawns 10million dollar figurines on the player, which is considered an "Invalid Model", since the game doesn't comprehend wtf is going on, it crashes the person who picks it up/sometimes causes you to crash in the process and spawning these figurines is easily detected by other modders and also does not normally work on them, either.

**Comment by AhmadToamah2010** [comment]
Ah okay I see thanks for helping!
