### ISSUE TITLE
Crashed by using chat options 

### ISSUE THREAD

**Issue by AhmadToamah2010** [Deadlineem/Extras-Addon-for-YimMenu#46]
Got crashed after pressing Extras Addon, Chat options, Addon info 
I get also randomly crashed after spamming Extras Addon, Chat options, Menu info 
coutlog : [17:05:26.0726385][FATAL/lua_module.cpp:80] attempt to index a boolean value
stack traceback:
	[C]: in ?
Please fix it @Deadlineem

**Comment by Deadlineem** [comment]
Looking into this right now, ill update this comment when i figure out what the issue is.

**Comment by AhmadToamah2010** [comment]
Okay

**Comment by AhmadToamah2010** [comment]
Yes i used after a while

**Comment by Deadlineem** [comment]
> Yes i used after a while

Its possible that Yim just by coincidence crashed due to how much you used the script/what options you used.  Periodically, go into Settings > Lua Scripts and press Reload All to make sure all the scripts have been stopped/refreshed if youre playing for an extended period of time. 

If there is an error with the script directly, it will output a line number and say "Extras-addon.lua" in the error of the cout.log

**Comment by AhmadToamah2010** [comment]
I will send u the cout.log
[04-01-2024-14-05-26_cout.log](https://github.com/Deadlineem/Extras-Addon-for-YimMenu/files/14826950/04-01-2024-14-05-26_cout.log)

**Comment by Deadlineem** [comment]
> I will send u the cout.log [04-01-2024-14-05-26_cout.log](https://github.com/Deadlineem/Extras-Addon-for-YimMenu/files/14826950/04-01-2024-14-05-26_cout.log)

Add my github name on discord ill add you to the discord channel, theres a sub-channel for bug reports

**Comment by AhmadToamah2010** [comment]
okay my name called ahmad4165

**Comment by Deadlineem** [comment]
> Got crashed after pressing Extras Addon, Chat options, Addon info I get also randomly crashed after spamming Extras Addon, Chat options, Menu info coutlog : [17:05:26.0726385][FATAL/lua_module.cpp:80] attempt to index a boolean value stack traceback: [C]: in ? Please fix it @Deadlineem

Also, please don't spam these options.  Its not meant for spamming, its meant to help others use the addon/menu and to help you easily explain what to do/where to go to get them when youre talking to others about it.
