### ISSUE TITLE
sir pls add more trolling features

### ISSUE THREAD

**Issue by THEKILERFRIEND** [Deadlineem/Extras-Addon-for-YimMenu#51]
pls add more crash, trolling features! it would make your addon really really good. (and make it so its not global only, tht u can use it on 1 person only. cus boat crash does whole lobby only.)

**Comment by THEKILERFRIEND** [comment]
oh and also. can u pls make it so the clown jet attack despawns maybe after a guy dies? or maybe add 2 types. ones that dont despawn, and ones that despawn. cause I kinda ruined a lobby by masskilling everyone on loop with jets

**Comment by Deadlineem** [comment]
Adding crashes would take a bit since its not easy to make them, the crashes in the global options are what they are meant to be, session wide.

Jets do despawn when they kill their target, they crash to the ground, when its spammed, there will be jets flying around that cant kill godmode players or jets that were supposed to target players that quit just roam.

**Comment by THEKILERFRIEND** [comment]
no bro. for me, when I used the jets, i kinda over spammed them. and then when I went back to a kid who i used it on, and I saw: the jets were still there.

**Comment by THEKILERFRIEND** [comment]
wait one last thing. could you add trolling features that someone could troll modders with? like maybe a trap thing. so it puts a jail around them every sec or sumn

**Comment by Deadlineem** [comment]
> wait one last thing. could you add trolling features that someone could troll modders with? like maybe a trap thing. so it puts a jail around them every sec or sumn

Spectate the player and use an object spawner.  The jets are intended to kill the player, so lets say you spawn 10 jets on 1 player, 1 jet kills the player, the other 9 may still linger around doing nothing.
