### ISSUE TITLE
How can i gift cars myself?

### ISSUE THREAD

**Issue by Toasty8i** [Deadlineem/Extras-Addon-for-YimMenu#52]

**Comment by Deadlineem** [comment]
Spawn in the car using the vehicle spawner in YimMenu (Vehicles > Spawner) modify it and drive it into LS customs.  
**This is a feature of YimMenu itself, not Extras addon so be sure you are not using the vehicle spawner under the Extras Addon tab**

> _No description provided._

**Comment by Toasty8i** [comment]
> Spawn in the car using the vehicle spawner in YimMenu (Vehicles > Spawner) modify it and drive it into LS customs. **This is a feature of YimMenu itself, not Extras addon so be sure you are not using the vehicle spawner under the Extras Addon tab**
> 
> > _No description provided._

Yeah i got it i forgot to select myself

**Comment by Toasty8i** [comment]
> Spawn in the car using the vehicle spawner in YimMenu (Vehicles > Spawner) modify it and drive it into LS customs. **This is a feature of YimMenu itself, not Extras addon so be sure you are not using the vehicle spawner under the Extras Addon tab**
> 
> > _No description provided._

i just noticed that the car doesnt save when i mod them? after i join a new session its still there but doesnt have modded designs anymore

**Comment by Deadlineem** [comment]
> > Spawn in the car using the vehicle spawner in YimMenu (Vehicles > Spawner) modify it and drive it into LS customs. **This is a feature of YimMenu itself, not Extras addon so be sure you are not using the vehicle spawner under the Extras Addon tab**
> > > _No description provided._
> 
> i just noticed that the car doesnt save when i mod them? after i join a new session its still there but doesnt have modded designs anymore

Because you cant use the gifting to gift it to yourself, its unneeded, read my first comment again.

**Comment by Toasty8i** [comment]
> > > Spawn in the car using the vehicle spawner in YimMenu (Vehicles > Spawner) modify it and drive it into LS customs. **This is a feature of YimMenu itself, not Extras addon so be sure you are not using the vehicle spawner under the Extras Addon tab**
> > > > _No description provided._
> > 
> > 
> > i just noticed that the car doesnt save when i mod them? after i join a new session its still there but doesnt have modded designs anymore
> 
> Because you cant use the gifting to gift it to yourself, its unneeded, read my first comment again.

oh thanks im stupid english is not my first language
