### ISSUE TITLE
The YimCEO doesnt fill crates

### ISSUE THREAD

**Issue by Toasty8i** [Deadlineem/Extras-Addon-for-YimMenu#53]

**Comment by Deadlineem** [comment]
> _No description provided._

Please provide descriptions to help us fix issues.  This is a known issue, you have to manually stock crates, unsure why this is, but the original untouched script is from https://www.unknowncheats.me/forum/grand-theft-auto-v/591335-yimceo-ceo-crates-method-yimmenu.html
