### ISSUE TITLE
Could you add this?

### ISSUE THREAD

**Issue by Toasty8i** [Deadlineem/Extras-Addon-for-YimMenu#55]
In Spawn Vehicle it would be nice if you could spawn Vehicles with modded liverys/tires like these
[1000_CARS.zip](https://github.com/Deadlineem/Extras-Addon-for-YimMenu/files/14985331/1000_CARS.zip)

**Comment by Deadlineem** [comment]
Probably could make a randomizer that will randomize the colors/liveries/modifications on the cars, but, you can already do this with YimMenu under Vehicles > LS Customs, though they do not spawn in with liveries and such.

**Comment by Toasty8i** [comment]
> Probably could make a randomizer that will randomize the colors/liveries/modifications on the cars, but, you can already do this with YimMenu under Vehicles > LS Customs, though they do not spawn in with liveries and such.

I know that i can change them i mean could you make like a tab where we can use the format of the cars in the .zip i linked so when i spawn a car its already tuned like this and i can give it to other people

**Comment by 6516516** [comment]
bro u can just save cars as u like with max tune than spown it will be as u like .. i have over 30 cars saved

**Comment by Deadlineem** [comment]
> bro u can just save cars as u like with max tune than spown it will be as u like .. i have over 30 cars saved

Indeed, yimmenu allows you to spawn/keep a car as it is.  Extras allows gifting to others.
