### ISSUE TITLE
add like xml maps into extras addon

### ISSUE THREAD

**Issue by THEKILERFRIEND** [Deadlineem/Extras-Addon-for-YimMenu#57]
add xml maps, and xml cars (aka like modded cars, maps) as a feature? imo it would be rlly cool as a built in feature bro

**Comment by Deadlineem** [comment]
YimMenu has this already built into it so there is no need for this.  Open your file explorer and type `%APPDATA%\YimMenu`

In there are 2 folders xml_maps and xml_vehicles
