### ISSUE TITLE
Improvement < Please add more crashes

### ISSUE THREAD

**Issue by AhmadToamah2010** [Deadlineem/Extras-Addon-for-YimMenu#58]
Hello @Deadlineem 
Can you add like more than 2 crash options please

**Comment by AhmadToamah2010** [comment]
Or could you add these invalid object crashes pls
    "proc_drygrasses01",
    "proc_drygrasses01b",
    "proc_brittlebush_01",
    "proc_forest_ivy_01",
    "proc_grassdandelion01",
    "proc_grasses01b",
    "proc_grassfronds01",
    "proc_grassplantmix_01",
    "proc_indian_pbrush_01",
    "proc_leafybush_01",
    "proc_lizardtail_01",
    "proc_lupins_01",
    "proc_meadowmix_01",
    "proc_meadowpoppy_01",
    "proc_desert_sage_01",
    "prop_saplin_001_b"

**Comment by Deadlineem** [comment]
Added more crashes, not sure if im going to do these models or not, but im closing for now, itll be in the archive for later
