### ISSUE TITLE
crashing when gifting car sometimes

### ISSUE THREAD

**Issue by Ruabc123** [Deadlineem/Extras-Addon-for-YimMenu#59]
when i spam the gift car sometimes it crashes but if i dont spam it then it doesnt work

**Comment by Deadlineem** [comment]
https://www.unknowncheats.me/forum/4064307-post101.html

Working to resolve

**Comment by rkwapisz** [comment]
I think one issue is that you're trying to reference a player via get_selected_player(), but that function simply returns the index of whatever play is selected in the YimMenu player list. Your vehicle gifting feature doesn't use the player menu, though, so what value is it pulling?

You may need to implement a player menu inside your vehicle gifting tab to get it to work more reliably.

**Comment by Deadlineem** [comment]
> I think one issue is that you're trying to reference a player via get_selected_player(), but that function simply returns the index of whatever play is selected in the YimMenu player list. Your vehicle gifting feature doesn't use the player menu, though, so what value is it pulling?
> 
> You may need to implement a player menu inside your vehicle gifting tab to get it to work more reliably.

The gifting system itself works, or, did before the last update.  get_selected_player() is the player that you select on YimMenu itself, so thats not the problem, mainly its just bc you have to take control of the player

**Comment by Deadlineem** [comment]
Altered the gifting system slightly thanks to WafflesGaming on UC, this should work now and not need to be spammed.
