### ISSUE TITLE
BUG - Player left and toxic actions going on us

### ISSUE THREAD

**Issue by heni015** [Deadlineem/Extras-Addon-for-YimMenu#61]
When we selected players from list, and Making Sandwich from him, or making explode, steam, flame etc. and he's going out from session then this atributes going on us. It's annoying, better to make it stop when player left.

**Comment by Deadlineem** [comment]
This is because it uses network.get_selected_player() and when there is no player selected bc they left, it defaults to yourself.

**Comment by heni015** [comment]
Yea, but it's stupid ^^
Better to check if targeted player left, then stop and clear target id? Something like that ^^

**Comment by Deadlineem** [comment]
I pushed a few fixes for some of these options today so they should not target you when someone quits.
