### ISSUE TITLE
Request  : SCH-LUA-YIMMENU  script  

### ISSUE THREAD

**Issue by 6516516** [Deadlineem/Extras-Addon-for-YimMenu#62]
can u guys add this script to extra addon ? this script has english version also .. its really nice and has a lot of options 

https://github.com/Drsexo/English-Sch-lua/

**Comment by AhmadToamah2010** [comment]
Yes, that would be nice, but I think he has to get permission first

**Comment by 6516516** [comment]
true ..we can just active  both scripts .. but its buggy somtimes

**Comment by Deadlineem** [comment]
> can u guys add this script to extra addon ? this script has english version also .. its really nice and has a lot of options
> 
> https://github.com/Drsexo/English-Sch-lua/

There are already some features from SCH-Lua in Extras.  I don't need permission, i just simply give credits where they are due.  If you have a list of more specific options you want to see in extras, i can import them from sch-lua for you, but i won't import the entire script.

**Comment by 6516516** [comment]
> > can u guys add this script to extra addon ? this script has english version also .. its really nice and has a lot of options
> > https://github.com/Drsexo/English-Sch-lua/
> 
> There are already some features from SCH-Lua in Extras. I don't need permission, i just simply give credits where they are due. If you have a list of more specific options you want to see in extras, i can import them from sch-lua for you, but i won't import the entire script.

thank u .. i tell u some : follow player  agrassive .. cage player ..ghost rider ... flame wing ... (and this is from other mod : turn into a big ball)... but you are right i saw the script u have added the most things .. i love u

**Comment by AhmadToamah2010** [comment]
And also all the available crashes from Sch-lua please

**Comment by Deadlineem** [comment]
In progress.  crashes and cages added
