### ISSUE TITLE
Addon functions broken: Shows 3 tabs with "**INVALID**"

### ISSUE THREAD

**Issue by hl2jeep** [Deadlineem/Extras-Addon-for-YimMenu#63]
title, not sure what is causing it, nothing i can see in the log files specifically, this happens if i inject in storymode or online. 
i disabled all my other addons just to make sure they're not conflicting, however the issue persists. i'm unable to use the vehicle gifting functions and the grief tab is entirely missing.

**Comment by Deadlineem** [comment]
> title, not sure what is causing it, nothing i can see in the log files specifically, this happens if i inject in storymode or online. i disabled all my other addons just to make sure they're not conflicting, however the issue persists. i'm unable to use the vehicle gifting functions and the grief tab is entirely missing.

can you provide some screenshots and maybe yimmenus cout.log if theres anything to do with extras-addon or any of the files related to it.  my username on discord is the same as github, feel free to add me there if you cant post the screenshots or cout.log here.

be sure that everything is updated to the latest version

vehicle gifting is no longer under the vehicle tab, instead it is supposed to appear when you click on a players name in the player list.

**Comment by hl2jeep** [comment]
> > title, not sure what is causing it, nothing i can see in the log files specifically, this happens if i inject in storymode or online. i disabled all my other addons just to make sure they're not conflicting, however the issue persists. i'm unable to use the vehicle gifting functions and the grief tab is entirely missing.
> 
> can you provide some screenshots and maybe yimmenus cout.log if theres anything to do with extras-addon or any of the files related to it. my username on discord is the same as github, feel free to add me there if you cant post the screenshots or cout.log here.
> 
> be sure that everything is updated to the latest version
> 
> vehicle gifting is no longer under the vehicle tab, instead it is supposed to appear when you click on a players name in the player list.

yeah sorry, didn't check, it shows up when clicking on player in the playerlist, however this is not described anywhere, not website or readme or features list, i highly recommend adding it somewhere so people don't get confused like me.
@Deadlineem

**Comment by Deadlineem** [comment]
> > > title, not sure what is causing it, nothing i can see in the log files specifically, this happens if i inject in storymode or online. i disabled all my other addons just to make sure they're not conflicting, however the issue persists. i'm unable to use the vehicle gifting functions and the grief tab is entirely missing.
> > 
> > 
> > can you provide some screenshots and maybe yimmenus cout.log if theres anything to do with extras-addon or any of the files related to it. my username on discord is the same as github, feel free to add me there if you cant post the screenshots or cout.log here.
> > be sure that everything is updated to the latest version
> > vehicle gifting is no longer under the vehicle tab, instead it is supposed to appear when you click on a players name in the player list.
> 
> yeah sorry, didn't check, it shows up when clicking on player in the playerlist, however this is not described anywhere, not website or readme or features list, i highly recommend adding it somewhere so people don't get confused like me. @Deadlineem

MY apologies!  That was one of the latest updates and I just haven't had the time to make sure i did everything is all.
