### ISSUE TITLE
crashes

### ISSUE THREAD

**Issue by mikedrugs** [Deadlineem/Extras-Addon-for-YimMenu#64]
when trying to spawn cars in a selected player, the game will randomly crash, this also happens with props

update: tested with no other luas co-loaded, still crashing, also the prop spawner starts to spam the "item spawned" notification, the preview stops working randomly and so on

other luas i'm using:
object_spawner
yim_actions

**Comment by Deadlineem** [comment]
Does this happen using the vehicle spawner in the addon itself alone or does it happen with Yims spawner too?

**Comment by mikedrugs** [comment]
> Does this happen using the vehicle spawner in the addon itself alone or does it happen with Yims spawner too?

only with the script, but also happens with props

**Comment by mikedrugs** [comment]
> > > Does this happen using the vehicle spawner in the addon itself alone or does it happen with Yims spawner too?
> > 
> > 
> > only with the script, but also happens with props
> 
> Is this with the props from animations? or with the object spawner?

it's only the object spawner and car spawner in the extras-addon script causing issues

**Comment by Deadlineem** [comment]
> > > > Does this happen using the vehicle spawner in the addon itself alone or does it happen with Yims spawner too?
> > > 
> > > 
> > > only with the script, but also happens with props
> > 
> > 
> > Is this with the props from animations? or with the object spawner?
> 
> it's only the object spawner and car spawner in the extras-addon script causing issues

The vehicle spawner under the vehicle options tab has been removed, it was causing them to crash.  Have not yet tested the object spawner, but the vehicle spawner in the selected player section should work fine now.

**Comment by xesdoog** [comment]
> The vehicle spawner under the vehicle options tab has been removed, it was causing them to crash.  Have not yet tested the object spawner, but the vehicle spawner in the selected player section should work fine now.

This could very well be related to that local issue we talked about

**Comment by mikedrugs** [comment]
![image](https://github.com/Deadlineem/Extras-Addon-for-YimMenu/assets/88536465/e8f3e258-a4e5-4e97-84ed-d459fba09d2d)
now i'm getting this error D:

**Comment by Deadlineem** [comment]
> ![image](https://private-user-images.githubusercontent.com/88536465/329777549-e8f3e258-a4e5-4e97-84ed-d459fba09d2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0NDI1NDEsIm5iZiI6MTcxNTQ0MjI0MSwicGF0aCI6Ii84ODUzNjQ2NS8zMjk3Nzc1NDktZThmM2UyNTgtYTRlNS00ZTk3LTg0ZWQtZDQ1OWZiYTA5ZDJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDE1NDQwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2YzA4ZDBhNzE4YmIyZTIxNGU0NTRmMjk2ZDZlYTdjYTM2YTM2ZWRkOWZmMWZiYWI5N2YwN2Q0YzhjNjIzYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bG7WLXH5THWnrQvGfJ6DATJYMXM2DeGVHRwNscMV1PI) now i'm getting this error D:

That has something to do with the spawnDistance sliders (X/Y/Z sliders).  I was testing this as well yesterday and the X slider works fine, Y slider didnt seem to do anything and didnt test Z

@xesdoog possibly, but it works fine aside from the small errors

**Comment by mikedrugs** [comment]
> > ![image](https://private-user-images.githubusercontent.com/88536465/329777549-e8f3e258-a4e5-4e97-84ed-d459fba09d2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0NDI1NDEsIm5iZiI6MTcxNTQ0MjI0MSwicGF0aCI6Ii84ODUzNjQ2NS8zMjk3Nzc1NDktZThmM2UyNTgtYTRlNS00ZTk3LTg0ZWQtZDQ1OWZiYTA5ZDJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDE1NDQwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2YzA4ZDBhNzE4YmIyZTIxNGU0NTRmMjk2ZDZlYTdjYTM2YTM2ZWRkOWZmMWZiYWI5N2YwN2Q0YzhjNjIzYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bG7WLXH5THWnrQvGfJ6DATJYMXM2DeGVHRwNscMV1PI) now i'm getting this error D:
> 
> That has something to do with the spawnDistance sliders (X/Y/Z sliders). I was testing this as well yesterday and the X slider works fine, Y slider didnt seem to do anything and didnt test Z. as for the crashing i believe that is fixed at least, the sliders aren't a major necessity lol
> 
> @xesdoog possibly, but the script works fine aside from the small errors like this.

alright, also the crashes are gone :)

**Comment by Deadlineem** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/88536465/329777549-e8f3e258-a4e5-4e97-84ed-d459fba09d2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0NDI1NDEsIm5iZiI6MTcxNTQ0MjI0MSwicGF0aCI6Ii84ODUzNjQ2NS8zMjk3Nzc1NDktZThmM2UyNTgtYTRlNS00ZTk3LTg0ZWQtZDQ1OWZiYTA5ZDJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDE1NDQwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2YzA4ZDBhNzE4YmIyZTIxNGU0NTRmMjk2ZDZlYTdjYTM2YTM2ZWRkOWZmMWZiYWI5N2YwN2Q0YzhjNjIzYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bG7WLXH5THWnrQvGfJ6DATJYMXM2DeGVHRwNscMV1PI) now i'm getting this error D:
> > 
> > 
> > That has something to do with the spawnDistance sliders (X/Y/Z sliders). I was testing this as well yesterday and the X slider works fine, Y slider didnt seem to do anything and didnt test Z. as for the crashing i believe that is fixed at least, the sliders aren't a major necessity lol
> > @xesdoog possibly, but the script works fine aside from the small errors like this.
> 
> alright, also the crashes are gone :)

Thanks for your help!  Im going to mess with the script some more tonight, i checked my cout.log and have that same error as above, didnt get the chance to work it out but i will.  If you run into any more crashes or issues dont hesitate to snap a screenshot.  Glad to hear its no longer crashing users, have you checked the object spawner as well?

**Comment by mikedrugs** [comment]
> > > > ![image](https://private-user-images.githubusercontent.com/88536465/329777549-e8f3e258-a4e5-4e97-84ed-d459fba09d2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0NDI1NDEsIm5iZiI6MTcxNTQ0MjI0MSwicGF0aCI6Ii84ODUzNjQ2NS8zMjk3Nzc1NDktZThmM2UyNTgtYTRlNS00ZTk3LTg0ZWQtZDQ1OWZiYTA5ZDJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDE1NDQwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2YzA4ZDBhNzE4YmIyZTIxNGU0NTRmMjk2ZDZlYTdjYTM2YTM2ZWRkOWZmMWZiYWI5N2YwN2Q0YzhjNjIzYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bG7WLXH5THWnrQvGfJ6DATJYMXM2DeGVHRwNscMV1PI) now i'm getting this error D:
> > > 
> > > 
> > > That has something to do with the spawnDistance sliders (X/Y/Z sliders). I was testing this as well yesterday and the X slider works fine, Y slider didnt seem to do anything and didnt test Z. as for the crashing i believe that is fixed at least, the sliders aren't a major necessity lol
> > > @xesdoog possibly, but the script works fine aside from the small errors like this.
> > 
> > 
> > alright, also the crashes are gone :)
> 
> Thanks for your help! Im going to mess with the script some more tonight, i checked my cout.log and have that same error as above, didnt get the chance to work it out but i will. If you run into any more crashes or issues dont hesitate to snap a screenshot. Glad to hear its no longer crashing users, have you checked the object spawner as well?

Hey :), after further testing and using it in my daily online trolling, sadly it still crashes and doesn't spawn vehicles to other players, maybe it's the other luas, yim just had an update that fixes crashes, i doubt that will fix anything but i'll see later

**Comment by mikedrugs** [comment]
after some testing seems to not crash anymore with the latest updates, the only thing i have noticed is that the object spawner kinda spams the notification :)

![image](https://github.com/Deadlineem/Extras-Addon-for-YimMenu/assets/88536465/97861a97-51f6-4f00-aa39-a7dd8a0313cb)

**Comment by Deadlineem** [comment]
> after some testing seems to not crash anymore with the latest updates, the only thing i have noticed is that the object spawner kinda spams the notification :)
> 
> ![image](https://private-user-images.githubusercontent.com/88536465/330004175-97861a97-51f6-4f00-aa39-a7dd8a0313cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2Mjc1NjMsIm5iZiI6MTcxNTYyNzI2MywicGF0aCI6Ii84ODUzNjQ2NS8zMzAwMDQxNzUtOTc4NjFhOTctNTFmNi00ZjAwLWFhMzktYTdkZDhhMDMxM2NiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDE5MDc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzMDViMjlhZDEwNWY4YTQ5NjcwZTkwODEwY2U4MTJkNWM0NzFlMDhkMDY1MjNmMzY0OTgzNDE0NDA1NGNmYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eVJqI51VajjnWl3P7uVQOglURY-l7gUe0zBFDsxJa-E)
> 
> Also my game crashed after using the model crash / fragment crash to 3 different people, but ig that's completely expected so don't mind this xD
> 
> [09:46:44.0223346][FATAL/lua_module.cpp:53] Lua is in a panic state and will now abort() the application [09:46:46.9493120][FATAL/lua_module.cpp:53] Lua is in a panic state and will now abort() the application
> 
> Edit again: crashes when trying to spawn a raiju (the plane) to a player, finally found the bug

I've been tweaking some of the things in the addon lately, get the latest version and retest if you dont mind, lmk if these are still a problem.

**Comment by mikedrugs** [comment]
Hey, apparently it doesn't crash anymore! i'm closing the issue, thank you!!, everything seems fine now.
