### ISSUE TITLE
Tab not work

### ISSUE THREAD

**Issue by KaifKol** [Deadlineem/Extras-Addon-for-YimMenu#66]
When using the script, the tab button in the game stops working

**Comment by Deadlineem** [comment]
Press insert and close the menu, then see if the tab button works.  Yimmenu disables control actions while the menu is up so you can navigate and type data into the menu without controlling your game.

**Comment by KaifKol** [comment]
there is no difference, the menu is closed, I can record a video

**Comment by KaifKol** [comment]
https://youtu.be/rzgAorgQ-Kc

**Comment by Deadlineem** [comment]
I looked into this.  The casino script (CasinoPacino) uses this

    if HUD.IS_PAUSE_MENU_ACTIVE() then
        PAD.DISABLE_CONTROL_ACTION(0, 348, true)
        PAD.DISABLE_CONTROL_ACTION(0, 204, true)
    end
    
    Control action 204 is the TAB button when the pause menu is active and 348 is the scroll wheel.  Not sure why the casino script needs this but if its an issue you can edit the script in notepad++, find line 3097 (or search for the above) and use -- to comment the line.  I will test when i have the time to see if this causes issues when disabled.

**Comment by KaifKol** [comment]
Thanks!!!!!

**Comment by Deadlineem** [comment]
> Thanks!!!!!

I got some more information as to why this is in there, you can read the comment from the creator of the casino script.

https://www.unknowncheats.me/forum/4082226-post30.html

He said "When ALT-Tabbing out of GTA, it causes a POI to be placed on the map" so thats why it is disabled.
