### ISSUE TITLE
i would like the return of an old function

### ISSUE THREAD

**Issue by ilpiruz** [Deadlineem/Extras-Addon-for-YimMenu#67]
the old ramming option was sometime better and sometime more fun than the nowdays "make npc drive to this player" i would like to have in the same time these two options, because there are sono scenarios where one function works better than the other one

**Comment by Deadlineem** [comment]
> the old ramming option was sometime better and sometime more fun than the nowdays "make npc drive to this player" i would like to have in the same time these two options, because there are sono scenarios where one function works better than the other one

If im not mistaken, the vehicle ram option was a very old option I created in Extras Addon.  This option was superseded by the "Vehicle Sandwich" option which now sandwiches the player between two vehicles, one that spawns below the map and travels upwards to the player and another that spawns above the player and travels downwards.

The vehicle ram was fun, however, did not kill the player as intended every time.

**Comment by ilpiruz** [comment]
yeah but i like it the same as sandwich and "npc drive to player" and also sometimes i want not to kill but troll, it would be funnier and less toxic

**Comment by Deadlineem** [comment]
> yeah but i like it the same as sandwich and "npc drive to player" and also sometimes i want not to kill but troll, it would be funnier and less toxic

I will add the vehicle ram feature in again, also give the addon an update and give the npc drive option a try, @USBMenus optimized it a bit ago, it might suit your needs until the ram feature is added

**Comment by ilpiruz** [comment]
and also the "npc drive to player" is unstable because sometimes the npcs are less smart than a money (no offense to the creator, hope the translator is not writing bad )

**Comment by Deadlineem** [comment]
> and also the "npc drive to player" is unstable because sometimes the npcs are less smart than a money (no offense to the creator, i hope the translator is not writing bad )

I fixed this today, give it a try with the latest and lmk how it works.  Should be massively improved now.

**Comment by ilpiruz** [comment]
trying it now, thanks

**Comment by Deadlineem** [comment]
> > > and also the "npc drive to player" is unstable because sometimes the npcs are less smart than a money (no offense to the creator, i hope the translator is not writing bad )
> > 
> > 
> > I fixed this today, give it a try with the latest and lmk how it works. Should be massively improved now.
> 
> idk but i can't see the option but i'm retrying

Not the ram feature, the npc drive to player

`if npcDrive:is_enabled() then
	if PLAYER.GET_PLAYER_PED(network.get_selected_player()) == PLAYER.PLAYER_PED_ID() then
				gui.show_message("NPC Drive","Stopped, player has left the session.")
				return
			end
        for _, veh in pairs(entities.get_all_vehicles_as_handles()) do
            ped = VEHICLE.GET_PED_IN_VEHICLE_SEAT(veh, -1, false)
            if ped ~= 0 and not PED.IS_PED_A_PLAYER(ped) then
                request_control(veh)
                request_control(ped)
                    --TASK.CLEAR_PRIMARY_VEHICLE_TASK(veh)
                    target = PLAYER.GET_PLAYER_PED(network.get_selected_player())
                    pos = ENTITY.GET_ENTITY_COORDS(target, true)
                    TASK.TASK_VEHICLE_DRIVE_TO_COORD(ped, veh, pos.x, pos.y, pos.z, 70.0, 1, ENTITY.GET_ENTITY_MODEL(veh), 16777216, 0.0, 1)
            end
        end
    end`

**Comment by ilpiruz** [comment]
oh then i probably misspelled, i just wanted the two versions of "npc drive to player" at the same time (the new and the one with the car coming from nowhere, the og one)

**Comment by Deadlineem** [comment]
> oh then i probably misspelled, i just wanted the two versions of "npc drive to player" at the same time (the new and the one with the car coming from nowhere, the og one)

Im aware, I will be adding that original vehicle ram feature back in at some point, just have alot of things to fix/polish before i get to it.  The NPC drive was not working as intended, it should now lol.

**Comment by Deadlineem** [comment]
> oh then i probably misspelled, i just wanted the two versions of "npc drive to player" at the same time (the new and the one with the car coming from nowhere, the og one)

Vehicle ram has been added back as per your request and severely improved

https://github.com/Deadlineem/Extras-Addon-for-YimMenu/commit/12870355094225aa2c37d54edffcd604a2b89aeb
