### ISSUE TITLE
newest crash method

### ISSUE THREAD

**Issue by THEKILERFRIEND** [Deadlineem/Extras-Addon-for-YimMenu#70]
The newest crash method is terrible. I tried it like 20x so far, and 19 times it crashed me instead of the guy I wanted to crash. plz remove it bro its useless

**Comment by Deadlineem** [comment]
Which one? Ik i added some that came from sch-lua as per request from another user but I didn't mess with the scripts for it just added it in.

**Comment by Deadlineem** [comment]
The model crash will be updated to work, however, i do not see much success with it crashing anybody, it simply spawns a bunch of large models on the targeted player which severely lags you as well.
