### ISSUE TITLE
Model Crash issue

### ISSUE THREAD

**Issue by YumoYo** [Deadlineem/Extras-Addon-for-YimMenu#71]
When using the model crash in the grief option against a modder it worked however when i went over to the city where we was the entire city was laggy, i was wondering if there was a way for when the person gets crashed the spawned in objs could get removed/deleted because i had to remove them myself

**Comment by Deadlineem** [comment]
This is an imported crash from SCH-Lua, i can attempt to make the objects despawn on their own, however, it may not crash the player as expected.

Until this is resolved you can go to the World tab in YimMenu and at the bottom of the window there is a delete option, check off vehicles and press delete all, itll make it easier to get rid of them.

**Comment by Deadlineem** [comment]
> > This is an imported crash from SCH-Lua, i can attempt to make the objects despawn on their own, however, it may not crash the player as expected.
> > Until this is resolved you can go to the World tab in YimMenu and at the bottom of the window there is a delete option, check off vehicles and press delete all, itll make it easier to get rid of them.
> 
> btw when the lua gets updated or what ever will there be a update log for it for the new features or anything that gets added?

Every time the script is updated on github there are logs for the features.  If you click this link https://github.com/Deadlineem/Extras-Addon-for-YimMenu/commits/main/

and then hover over the "Update Extras-Addon.lua" commits link, there is usually a short description of updates, you can see in the screenshot.
![Screenshot_69](https://github.com/Deadlineem/Extras-Addon-for-YimMenu/assets/24372625/1712b362-2842-4516-8930-78f04fe81c74)

**Comment by Deadlineem** [comment]
> > > > This is an imported crash from SCH-Lua, i can attempt to make the objects despawn on their own, however, it may not crash the player as expected.
> > > > Until this is resolved you can go to the World tab in YimMenu and at the bottom of the window there is a delete option, check off vehicles and press delete all, itll make it easier to get rid of them.
> > > 
> > > 
> > > btw when the lua gets updated or what ever will there be a update log for it for the new features or anything that gets added?
> > 
> > 
> > Every time the script is updated on github there are logs for the features. If you click this link https://github.com/Deadlineem/Extras-Addon-for-YimMenu/commits/main/
> > and then hover over the "Update Extras-Addon.lua" commits link, there is usually a short description of updates, you can see in the screenshot. ![Screenshot_69](https://private-user-images.githubusercontent.com/24372625/333680400-1712b362-2842-4516-8930-78f04fe81c74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1ODI1OTAsIm5iZiI6MTcxNjU4MjI5MCwicGF0aCI6Ii8yNDM3MjYyNS8zMzM2ODA0MDAtMTcxMmIzNjItMjg0Mi00NTE2LTg5MzAtNzhmMDRmZTgxYzc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDIwMjQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwZGE1YzU5NzJmNjVhMmViZjllZDE4NzkxYjFmNDQ5OTBlMzZiZTAyNTgzZDhmOTlkODE4MDdkZWRiNjVlYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KsIc2691H-3PLB7gJW6RIylOVctr6aRMBfu7TWMhou0)
> 
> ah didnt know that lol, thanks.

Most people don't, its no problem!  Honestly imo i feel like the notes should have its own dedicated tab on git instead but thats just my opinion.
