### ISSUE TITLE
mistake? idk 

### ISSUE THREAD

**Issue by n8tr0** [Deadlineem/Extras-Addon-for-YimMenu#73]
Is this a mistake? "locallocals"

https://github.com/Deadlineem/Extras-Addon-for-YimMenu/blob/83cdb9bb919ec4ea3d1dc86e4b3f5d450747f7a1/Extras-Addon.lua#L3103

**Comment by Deadlineem** [comment]
Yep!  Thanks for catching this, good eye!

**Comment by USBMenus** [comment]
> Back again
> 
> https://github.com/Deadlineem/Extras-Addon-for-YimMenu/blob/a5a3f69cbb946e78294b576380cb187530379a1a/Extras-Addon.lua#L3129

sure is, fixed it

**Comment by Deadlineem** [comment]
> > Back again
> > https://github.com/Deadlineem/Extras-Addon-for-YimMenu/blob/a5a3f69cbb946e78294b576380cb187530379a1a/Extras-Addon.lua#L3129
> 
> sure is, fixed it

I fixed this before when he mentioned it, i think i reverted this without realizing -_- lmao
