### ISSUE TITLE
Request : No Fog

### ISSUE THREAD

**Issue by n8tr0** [Deadlineem/Extras-Addon-for-YimMenu#76]
Is it possible to add a button to disable fog, like:
`GRAPHICS.SET_TIMECYCLE_MODIFIER(”INT_NO_fogALPHA“)`
Thx

**Comment by Deadlineem** [comment]
This would most likely just end up being a weather selection dropdown

see these natives from nativedb for reference
![Screenshot_95](https://github.com/Deadlineem/Extras-Addon-for-YimMenu/assets/24372625/a6e78338-be3f-41f8-8040-9a9a6bd6a795)

**Comment by Deadlineem** [comment]
> It's not the same in YIM the TIMECYCLE “INT_NO_fogALPHA” looks like this: (I've added it to sch to show you) https://github.com/Deadlineem/Extras-Addon-for-YimMenu/assets/150055725/92de1659-b5ad-4b07-9a23-74ca4cc2b171

Ahh ok i see what you mean now.  So setting said option does that, any others to add to it or just a solo option?

**Comment by Deadlineem** [comment]
When im home from work i can add these options to extras, i will probably make an array with a list of valid, working usable time cycle modifiers and out then in a combo or listbox with a toggle for on/off.

If you know how to do it you can also feel free to contribute to extras, always welcome new help because more people = more features and more bug fixes.

**Comment by Deadlineem** [comment]
> > > It's not the same in YIM the TIMECYCLE “INT_NO_fogALPHA” looks like this: (I've added it to sch to show you) https://github.com/Deadlineem/Extras-Addon-for-YimMenu/assets/150055725/92de1659-b5ad-4b07-9a23-74ca4cc2b171
> > 
> > 
> > Ahh ok i see what you mean now. So setting said option does that, any others to add to it or just a solo option?
> 
> I personally only use “no fog” (INT_NO_fogALPHA)” But there is a multitude of ‘TIMECYCLE’ that can be added, like sch with "Heavy fog" (casino_main_floor_heist) and more..



> > > It's not the same in YIM the TIMECYCLE “INT_NO_fogALPHA” looks like this: (I've added it to sch to show you) https://github.com/Deadlineem/Extras-Addon-for-YimMenu/assets/150055725/92de1659-b5ad-4b07-9a23-74ca4cc2b171
> > 
> > 
> > Ahh ok i see what you mean now. So setting said option does that, any others to add to it or just a solo option?
> 
> I personally only use “no fog” (INT_NO_fogALPHA)” But there is a multitude of ‘TIMECYCLE’ that can be added, like sch with "Heavy fog" (casino_main_floor_heist) and more..



> > > It's not the same in YIM the TIMECYCLE “INT_NO_fogALPHA” looks like this: (I've added it to sch to show you) https://github.com/Deadlineem/Extras-Addon-for-YimMenu/assets/150055725/92de1659-b5ad-4b07-9a23-74ca4cc2b171
> > 
> > 
> > Ahh ok i see what you mean now. So setting said option does that, any others to add to it or just a solo option?
> 
> I personally only use “no fog” (INT_NO_fogALPHA)” But there is a multitude of ‘TIMECYCLE’ that can be added, like sch with "Heavy fog" (casino_main_floor_heist) and more..

Added a listbox, search function and the entire list of timecycles, enjoy :)
