### ISSUE TITLE
Problem with the new submenu 

### ISSUE THREAD

**Issue by ilpiruz** [Deadlineem/Extras-Addon-for-YimMenu#81]
i can't move the new submenus and also i prefer the old one because it was tidy

**Comment by rr1231234** [comment]
Also the money remover dont work no more

**Comment by Deadlineem** [comment]
> Also the money remover dont work no more

I just tested the money remover and it does work, you're doing it wrong.  Put an amount in the box and press the button, then you need to open the in-game interaction menu, go to 

Health & Ammo > Ballistic Equipment Services > Request Ballistic Equipment

the set amount should be there like so:
![Screenshot_121](https://github.com/Deadlineem/Extras-Addon-for-YimMenu/assets/24372625/f9fdb3cb-58d3-432d-af56-acec1ddb37e1)
![Screenshot_122](https://github.com/Deadlineem/Extras-Addon-for-YimMenu/assets/24372625/2c4df7da-2397-4481-82d7-1fd951c26cf9)

Then just simply request it.

**Comment by Deadlineem** [comment]
> i can't move the new submenus and also i prefer the old one because it was tidy

They arent movable like the old one was with the debug window.  Not sure if i can make them movable or not.

**Comment by ilpiruz** [comment]
the problem is not only they aren't movable, but also they are half out of the screen

**Comment by Deadlineem** [comment]
> the problem is not only they aren't movable, but also they are half out of the screen

Pushing an update now that makes the submenus movable!!!
