### ISSUE TITLE
Almost perfect

### ISSUE THREAD

**Issue by ilpiruz** [Deadlineem/Extras-Addon-for-YimMenu#83]
the first issue is that the game crashes, but i don't know if it's related to the new yimmenu update
and the second one is that every time i close the yimmenu gui, the extras menu resets every floating window status and position

**Comment by Deadlineem** [comment]
> the first issue is that the game crashes, but i don't know if it's related to the new yimmenu update and the second one is that every time i close the yimmenu gui, the extras menu resets every floating window status and position

Not sure why the game would crash, check %appdata%\YimMenu\cout.log for console output and possible answers to your crashing.

Second, there is no saving on the windows at this time, yes i know its annoying but i have to edit the default positions a bit and try to get it to save the user input location, but they can be moved out of the way or on screen now and that the main part.

**Comment by Deadlineem** [comment]
> the first issue is that the game crashes, but i don't know if it's related to the new yimmenu update and the second one is that every time i close the yimmenu gui, the extras menu resets every floating window status and position



> the first issue is that the game crashes, but i don't know if it's related to the new yimmenu update and the second one is that every time i close the yimmenu gui, the extras menu resets every floating window status and position

Fixed this, the default window positions should now all appear in these locations and can be moved freely or resized as well.

![Screenshot_126](https://github.com/Deadlineem/Extras-Addon-for-YimMenu/assets/24372625/f55d4534-0fe5-47a9-a8c7-3fae75494f43)

**Comment by Deadlineem** [comment]
Tabs are now automatically collapsed instead of opened and can also be resized and moved around to different locations on the screen.

Vehicle Gifting now deletes invisible vehicles for you as long as you are within the range of them AND automatically sends a chat message to the receiving player.  -- Thanks to hexarobi

Custom Wheel listboxes now show beside one another as to not take up so much space.
