### ISSUE TITLE
Request: Add Indirect viewing from SCH Lua

### ISSUE THREAD

**Issue by Netamaru** [Deadlineem/Extras-Addon-for-YimMenu#84]
Add Indirect viewing because it's not easily get detected when spectating others

**Comment by Deadlineem** [comment]
> Add Indirect viewing because it's not easily get detected when spectating others

Added indirect viewing a requested, also positioned it properly as well and added a slider for adjusting the camera distance.

https://github.com/Deadlineem/Extras-Addon-for-YimMenu/assets/24372625/8092c614-755b-4e25-bc23-91e022552db5
