### ISSUE TITLE
[BUG]  Business Manager >Agency shows wrong items

### ISSUE THREAD

**Issue by rjp421** [Deadlineem/Extras-Addon-for-YimMenu#86]
When choosing Business Manager > Agency, it seems to be showing the wrong items in the list.

[https://i.imgur.com/WVDqBVJ.png](https://i.imgur.com/WVDqBVJ.png)

Thank you for the work, great addon!

**Comment by Deadlineem** [comment]
Woah, that IS indeed wrong, does this happen right off the bat or does it happen after using for awhile?

  @USBMenus @xesdoog can one of you look into this and push a fix if possible?

**Comment by rjp421** [comment]
This appears to be happening right away.

Launch game > Story Mode > inject YimMenu > join solo session.

Skip Cooldown seems to work, but the Complete Preps does not.

Thanks!

**Comment by Deadlineem** [comment]
> This appears to be happening right away.
> 
> Launch game > Story Mode > inject YimMenu > join solo session.
> 
> Skip Cooldown seems to work, but the Complete Preps does not.
> 
> Thanks!

Thanks for the info, it seems there were two tables with the same names so it was causing ossues, which also explains the complete preps option as well siñce it couldnt locate the proper information from the table.  A PR should be coming soon to fix this.
