### ISSUE TITLE
[BUG]  Gift Vehicle not working

### ISSUE THREAD

**Issue by rjp421** [Deadlineem/Extras-Addon-for-YimMenu#92]
When trying to Gift a vehicle to someone by following the directions, as soon as i click Gift Vehicle, it says Success but kicks them from the vehicle and they are unable to get back in.

I can drive the gifted vehicle, but the other player cannot.

Using YimMenu build 61ddba1 from today.

**Comment by Deadlineem** [comment]
> When trying to Gift a vehicle to someone by following the directions, as soon as i click Gift Vehicle, it says Success but kicks them from the vehicle and they are unable to get back in.
> 
> I can drive the gifted vehicle, but the other player cannot.
> 
> Using YimMenu build 61ddba1 from today.

We are aware of this issue, it is a known issue due to the latest update to gta which patched vehicle gifting in all mod menus.  We are unsure at this time of there will be a fix.

**Comment by rjp421** [comment]
Ok, Thanks.
