### ISSUE TITLE
Smart global crashes only for non modders (anti token spoofing)

### ISSUE THREAD

**Issue by mikedrugs** [Deadlineem/Extras-Addon-for-YimMenu#95]
Can we have an option to crash the entire session BUT the host token spoofers/detected modders?, if we implement this method it wont notify them about someone trying to crash, and we wont get kicked by the token spoofers.

Got this idea while someone took the host for the sole purpose of griefing without getting desync kicked, then i proceeded to crash the entire lobby, the lobby was dead but at the end i got kicked because he got the alerts

**Comment by Deadlineem** [comment]
If i implemented another crash into Extras, it would not directly target only non-modders, its all or nothing honestly, if anything I would prefer one that crashes tf out of any modder, host or not.

**Comment by mikedrugs** [comment]
> If i implemented another crash into Extras, it would not directly target only non-modders, its all or nothing honestly, if anything I would prefer one that crashes tf out of any modder, host or not.

My idea is about adding like a checkbox to filter detected modders or token spoofing, making it more versatile for different purposes, this could be used against malicious token spoofers, you kill the entire session forcing him to give up host or switch sessions

**Comment by Deadlineem** [comment]
> > If i implemented another crash into Extras, it would not directly target only non-modders, its all or nothing honestly, if anything I would prefer one that crashes tf out of any modder, host or not.
> 
> My idea is about adding like a checkbox to filter detected modders or token spoofers, making it more versatile for different purposes, this could be used against malicious token spoofers, you kill the entire session forcing him to give up host or switch sessions
> 
> I didn't mean like a new whole crash method, just a way to filter people from the current crash methods we have

That would more be a question to suggest on the base version of YimMenu, not the extras addon

**Comment by mikedrugs** [comment]
> > > If i implemented another crash into Extras, it would not directly target only non-modders, its all or nothing honestly, if anything I would prefer one that crashes tf out of any modder, host or not.
> > 
> > 
> > My idea is about adding like a checkbox to filter detected modders or token spoofers, making it more versatile for different purposes, this could be used against malicious token spoofers, you kill the entire session forcing him to give up host or switch sessions
> > I didn't mean like a new whole crash method, just a way to filter people from the current crash methods we have
> 
> That would more be a question to suggest on the base version of YimMenu, not the extras addon, i do not think lua has the capabilities to pull the detected modder information.

thats sad, i thought yim luas could pull the detected modder info

**Comment by Deadlineem** [comment]
> > > > If i implemented another crash into Extras, it would not directly target only non-modders, its all or nothing honestly, if anything I would prefer one that crashes tf out of any modder, host or not.
> > > 
> > > 
> > > My idea is about adding like a checkbox to filter detected modders or token spoofers, making it more versatile for different purposes, this could be used against malicious token spoofers, you kill the entire session forcing him to give up host or switch sessions
> > > I didn't mean like a new whole crash method, just a way to filter people from the current crash methods we have
> > 
> > 
> > That would more be a question to suggest on the base version of YimMenu, not the extras addon, i do not think lua has the capabilities to pull the detected modder information.
> 
> thats sad, i thought yim luas could pull the detected modder info

Its possible, but as far as I know, it doesn't.  I can look into it and get back to you though.

**Comment by binded-zz** [comment]
if there modders and you have the modder detect reaction and shit 
they are auto added to the PD pull the list of active in session and comapre it against the PD
im sure that they added pd access to the lua 

what i wold like to see is maybe a extras player/user database  page where it just redraws a whole new windows like you already get  with the base menu but just a extras version of it with all the the hacks and player commands on its own  click name and open on the side with all the actions to the side 
it wold help with all the extra windows and i think it would stop messing with other scripts like schs adding all the extra stuff to the bottom of players tab

but like on the root menu so like 
blah 
blah
blah 
network
settings
extras
extras-players-controls-db 
casino
harmless
something like that 
then when you click on extras players you get the players tab but lua instead rather then the base hard coded tab

no one is going to be adding extra stuff the extras players tab
like they do with the players tab

i would think that would fix the debug window issues 

it wouldnt be as easy as just clicking a player 
but it would only be 1 click more 

i thought about trying this but couldnt figure it out and i think there will be alot of imgui commands in the lua

so i pretty much mean another player database looking tab  usersleft scroll with active in session list maybe a select box to change to the database right side options

**Comment by mikedrugs** [comment]
> > > > > If i implemented another crash into Extras, it would not directly target only non-modders, its all or nothing honestly, if anything I would prefer one that crashes tf out of any modder, host or not.
> > > > 
> > > > 
> > > > My idea is about adding like a checkbox to filter detected modders or token spoofers, making it more versatile for different purposes, this could be used against malicious token spoofers, you kill the entire session forcing him to give up host or switch sessions
> > > > I didn't mean like a new whole crash method, just a way to filter people from the current crash methods we have
> > > 
> > > 
> > > That would more be a question to suggest on the base version of YimMenu, not the extras addon, i do not think lua has the capabilities to pull the detected modder information.
> > 
> > 
> > thats sad, i thought yim luas could pull the detected modder info
> 
> Its possible, but as far as I know, it doesn't. I can look into it and get back to you though. IF you want to just crash non modders, use the boat skin crash, it usually leaves the modders in the session.

Yeah but the thing is, i dont want to spawn props or send crash stuff to these modders, i dont want them to notice me so i dont get kicked, thats the point

**Comment by Deadlineem** [comment]
> > > > > > If i implemented another crash into Extras, it would not directly target only non-modders, its all or nothing honestly, if anything I would prefer one that crashes tf out of any modder, host or not.
> > > > > 
> > > > > 
> > > > > My idea is about adding like a checkbox to filter detected modders or token spoofers, making it more versatile for different purposes, this could be used against malicious token spoofers, you kill the entire session forcing him to give up host or switch sessions
> > > > > I didn't mean like a new whole crash method, just a way to filter people from the current crash methods we have
> > > > 
> > > > 
> > > > That would more be a question to suggest on the base version of YimMenu, not the extras addon, i do not think lua has the capabilities to pull the detected modder information.
> > > 
> > > 
> > > thats sad, i thought yim luas could pull the detected modder info
> > 
> > 
> > Its possible, but as far as I know, it doesn't. I can look into it and get back to you though. IF you want to just crash non modders, use the boat skin crash, it usually leaves the modders in the session.
> 
> Yeah but the thing is, i dont want to spawn props or send crash stuff to these modders, i dont want them to notice me so i dont get kicked, thats the point

You could just set Legit force host and kick the host player, take host and then host kick modders so you dont have to deal with it.  Thats what I do

**Comment by Deadlineem** [comment]
> if there modders and you have the modder detect reaction and shit they are auto added to the PD pull the list of active in session and comapre it against the PD im sure that they added pd access to the lua
> 
> what i wold like to see is maybe a extras player/user database page where it just redraws a whole new windows like you already get with the base menu but just a extras version of it with all the the hacks and player commands on its own click name and open on the side with all the actions to the side it wold help with all the extra windows and i think it would stop messing with other scripts like schs adding all the extra stuff to the bottom of players tab
> 
> but like on the root menu so like blah blah blah network settings extras extras-players-controls-db casino harmless something like that then when you click on extras players you get the players tab but lua instead rather then the base hard coded tab
> 
> no one is going to be adding extra stuff the extras players tab like they do with the players tab
> 
> i would think that would fix the debug window issues
> 
> it wouldnt be as easy as just clicking a player but it would only be 1 click more
> 
> i thought about trying this but couldnt figure it out and i think there will be alot of imgui commands in the lua
> 
> so i pretty much mean another player database looking tab usersleft scroll with active in session list maybe a select box to change to the database right side options

This was talked about in the discord channel a few times, but was never put into play in extras.  It would be nice to have but in the same token, YimMenu's GUI system is somewhat difficult to work with, it was hell just adding my own custom tabs to the GUI and positioning them/getting them to expand/collapse the right way.

**Comment by mikedrugs** [comment]
This issue can now be closed as theres no way to pull active modder data which ruins the whole point of the original post, i hope yim improves their lua apis

**Comment by Deadlineem** [comment]
> This issue can now be closed as theres no way to pull active modder data which ruins the whole point of the original post, i hope yim improves their lua apis

is_player_flagged_as_modder(player_idx) may be what we are looking for with that.  If so, utilizing this in lua could potentially remove them from the players the crash/kicks are sent to.  you can thank @USBMenus for this find.

Now, this will probably be something I would add to settings as a toggle like (Don't Target Modders) or something and it would work on basically every feature when enabled.

**Comment by binded-zz** [comment]
you can also pull the modder reason i think all infractions
that was added back a while ago 
when they added some player database stuff to lua

thats why i said you can scan the player database for already listed modders 
i thought you knew this

**Comment by Deadlineem** [comment]
> you can also pull the modder reason i think all infractions that was added back a while ago when they added some player database stuff to lua
> 
> thats why i said you can scan the player database for already listed modders i thought you knew this

Nope, i had no idea you could do that.  I do now though, and yes u can see their detection reason aka "Infractions"
get_flagged_modder_reason(player_idx)

**Comment by mikedrugs** [comment]
> > This issue can now be closed as theres no way to pull active modder data which ruins the whole point of the original post, i hope yim improves their lua apis
> 
> is_player_flagged_as_modder(player_idx) may be what we are looking for with that. If so, utilizing this in lua could potentially remove them from the players the crash/kicks are sent to. you can thank @USBMenus for this find.
> 
> Now, this will probably be something I would add to settings as a toggle like (Don't Target Modders) or something and it would work on basically every feature when enabled.

thats really cool! would be awesome to have this

**Comment by Deadlineem** [comment]
> > > This issue can now be closed as theres no way to pull active modder data which ruins the whole point of the original post, i hope yim improves their lua apis
> > 
> > 
> > is_player_flagged_as_modder(player_idx) may be what we are looking for with that. If so, utilizing this in lua could potentially remove them from the players the crash/kicks are sent to. you can thank @USBMenus for this find.
> > Now, this will probably be something I would add to settings as a toggle like (Don't Target Modders) or something and it would work on basically every feature when enabled.
> 
> thats really cool! would be awesome to have this, as i said, this has a lot of value for when you want to do global stuff without getting other modders attention or getting kicked by some token spoofer

This feature was decided against, however, something similar exists now "Auto Host Kick" that kicks the host if they aren't a modder, if they are it wont do anything to them, from here you can modify the feature yourself to achieve this if youd like, but this feature seems a bit too toxic for extras.
