### ISSUE TITLE
[Suggestion] Cayo Perico Heist Editor add Teleport Bring All

### ISSUE THREAD

**Issue by rjp421** [Deadlineem/Extras-Addon-for-YimMenu#97]
Thanks for adding the last teleports!

Another frequently used option is the YimMenu>Network>Controls>Bring All button.

Would it be possible to add this to the Teleports also?

Very helpful for helping the team move around.

Great Extras, thanks again!

**Comment by Deadlineem** [comment]
> Thanks for adding the last teleports!
> 
> Another frequently used option is the YimMenu>Network>Controls>Bring All button.
> 
> Would it be possible to add this to the Teleports also?
> 
> Very helpful for helping the team move around.
> 
> Great Extras, thanks again!

I was also pondering this when i was adding the teleports in the cayo, id like to make this a feature as well because it would be much faster to bring them to you and keep them from dying.
